// Code generated by OctGen. DO NOT EDIT.
// OctGen model: tspack-concepts.v1 (experimental).
package concepts

func builtinFragments() []Fragment {
	return []Fragment{Fragment{Name: "tspack.workspace", Description: "TSPack workspace shell",
		Provides: []string{"tspack.workspace"},

		Manifest: ManifestContributions{Workspace: &WorkspaceContribution{Name: "workspace"}, Concepts: []string{"tspack.workspace"}}},

		Fragment{Name: "tspack.manifestBoundary",
			Provides: []string{"tspack.manifestBoundary"}, Requires: []string{"tspack.workspace"},

			Manifest: ManifestContributions{Tools: []DependencyContribution{DependencyContribution{Name: "@biomejs/biome", Range: "^1.9.4", Source: "npm"}},

				Concepts: []string{"tspack.manifestBoundary"}}},

		Fragment{Name: "tspack.securityPolicy",
			Provides: []string{"tspack.securityPolicy"},

			Manifest: ManifestContributions{SecurityPolicy: []PolicyContribution{PolicyContribution{Subject: "npm", Action: "acknowledge", Range: "baseline"}},

				Concepts: []string{"tspack.securityPolicy"}}},

		Fragment{Name: "tspack.updatePolicy",
			Provides: []string{"tspack.updatePolicy"},

			Manifest: ManifestContributions{UpdatePolicy: []PolicyContribution{PolicyContribution{Subject: "dependencies", Action: "pin", Range: "minor"}},

				Concepts: []string{"tspack.updatePolicy"}}},

		Fragment{Name: "typescript.app",
			Provides: []string{"typescript.app"}, CompatibleKinds: []string{"app"},

			Manifest: ManifestContributions{Tools: []DependencyContribution{DependencyContribution{Name: "typescript", Range: "^5.0.0", Source: "npm"}},

				Concepts: []string{"typescript.app"}}},

		Fragment{Name: "vite.app",
			Provides: []string{"vite.app"}, Requires: []string{"typescript.app"},
			CompatibleKinds: []string{"app"},

			Manifest: ManifestContributions{Tools: []DependencyContribution{DependencyContribution{Name: "vite", Range: "^5.0.0", Source: "npm"}},

				RunTargets: []RunTargetContribution{RunTargetContribution{Name: "dev",
					Command: "vite"},

					RunTargetContribution{Name: "build", Command: "vite build"},

					RunTargetContribution{Name: "preview", Command: "vite preview"}},

				Concepts: []string{"vite.app"}}},

		Fragment{Name: "react.app",
			Provides: []string{"react.app"}, Requires: []string{"typescript.app", "browser.spa"},
			Conflicts: []string{"react.library"}, CompatibleKinds: []string{"app"},

			Manifest: ManifestContributions{Dependencies: []DependencyContribution{DependencyContribution{Name: "react", Range: "^19.0.0", Source: "npm"},

				DependencyContribution{Name: "react-dom", Range: "^19.0.0", Source: "npm"}},

				Tools: []DependencyContribution{DependencyContribution{Name: "@vitejs/plugin-react",
					Range: "^4.0.0", Source: "npm"},

					DependencyContribution{Name: "@types/react", Range: "^19.0.0", Source: "npm"},

					DependencyContribution{Name: "@types/react-dom", Range: "^19.0.0", Source: "npm"}},

				Concepts: []string{"react.app"}}},

		Fragment{Name: "browser.spa",
			Provides: []string{"browser.spa"}, Conflicts: []string{"react.library"},
			CompatibleKinds: []string{"app"},

			Manifest: ManifestContributions{Targets: []TargetContribution{TargetContribution{Name: "app", Export: ".", Entry: "src/main.tsx",
				Runtime: "dist/main.js", Types: "dist/main.d.ts"}},

				Concepts: []string{"browser.spa"}}},

		Fragment{Name: "browser.static",
			Provides: []string{"browser.static"}, Requires: []string{"vite.app"},
			CompatibleKinds: []string{"app"},

			Manifest: ManifestContributions{Targets: []TargetContribution{TargetContribution{Name: "app", Export: ".", Entry: "src/main.ts",
				Runtime: "dist/main.js", Types: "dist/main.d.ts"}},

				Concepts: []string{"browser.static"}}},

		Fragment{Name: "typescript.library",
			Provides: []string{"typescript.library"}, CompatibleKinds: []string{"library"},

			Manifest: ManifestContributions{Tools: []DependencyContribution{DependencyContribution{Name: "typescript", Range: "^5.0.0", Source: "npm"}},

				RunTargets: []RunTargetContribution{RunTargetContribution{Name: "build-types",
					Command: "tsc -p tsconfig.build.json --listEmittedFiles"},

					RunTargetContribution{Name: "typecheck", Command: "tsc -p tsconfig.json --noEmit --pretty false --diagnostics"}},

				Concepts: []string{"typescript.library"}}},

		Fragment{Name: "vite.library",
			Provides: []string{"vite.library"}, Requires: []string{"typescript.library"},
			CompatibleKinds: []string{"library"},

			Manifest: ManifestContributions{Tools: []DependencyContribution{DependencyContribution{Name: "vite", Range: "^5.0.0", Source: "npm"}},

				RunTargets: []RunTargetContribution{RunTargetContribution{Name: "build",
					Command: "vite build"}},

				Concepts: []string{"vite.library"}}},

		Fragment{Name: "package.peerDependencies",
			Provides: []string{"package.peerDependencies"}, CompatibleKinds: []string{"library"},

			Manifest: ManifestContributions{Concepts: []string{"package.peerDependencies"}}},

		Fragment{Name: "react.library",
			Provides: []string{"react.library"},

			Requires: []string{"package.peerDependencies", "package.exports", "tspack.pack", "vite.library", "typescript.library"}, Conflicts: []string{"browser.spa", "react.app"},
			CompatibleKinds: []string{"library"},

			Manifest: ManifestContributions{Tools: []DependencyContribution{DependencyContribution{Name: "@vitejs/plugin-react", Range: "^4.0.0", Source: "npm"},

				DependencyContribution{Name: "@types/react", Range: "^19.0.0", Source: "npm"},

				DependencyContribution{Name: "@types/react-dom", Range: "^19.0.0", Source: "npm"}},

				Peers: []DependencyContribution{DependencyContribution{Name: "react",
					Range: "^19.0.0", Source: "npm"},

					DependencyContribution{Name: "react-dom", Range: "^19.0.0", Source: "npm"}},

				Targets: []TargetContribution{TargetContribution{Name: "library",
					Export: ".", Entry: "src/index.ts", Runtime: "dist/index.js",
					Types: "dist/index.d.ts"}},

				Concepts: []string{"react.library"}}},

		Fragment{Name: "package.exports",
			Provides: []string{"package.exports"}, CompatibleKinds: []string{"library"},

			Manifest: ManifestContributions{Concepts: []string{"package.exports"}},

			Projections: ProjectionContributions{Objects: map[string]map[string]string{"package.exports": map[string]string{".": "./dist/index.js"}}}},

		Fragment{Name: "tspack.pack", Provides: []string{"tspack.pack"},
			CompatibleKinds: []string{"library"},

			Manifest: ManifestContributions{Pack: &PackContribution{Format: "npm", Artifact: "dist"}, Concepts: []string{"tspack.pack"}}}}
}
