// Code generated by OctGen. DO NOT EDIT.
// OctGen model: tspack-concepts.v1 (experimental).
package concepts

type generatedCompositionCase struct {
	Name         string
	Kind         string
	Concepts     []string
	Dependencies []string
	Tools        []string
	Peers        []string
	Targets      []string
	RunTargets   []string
	Projections  []string
	HasPack      bool
}

var generatedBuiltinNames []string = []string{"tspack.workspace", "tspack.manifestBoundary",
	"tspack.securityPolicy", "tspack.updatePolicy", "typescript.app", "vite.app", "react.app", "browser.spa", "browser.static", "typescript.library", "vite.library", "package.peerDependencies",
	"react.library", "package.exports", "tspack.pack"}
var generatedBuiltinCompositionCases []generatedCompositionCase = []generatedCompositionCase{generatedCompositionCase{Name: "static-app", Kind: "app",
	Concepts: []string{"browser.static", "vite.app", "typescript.app", "tspack.workspace",
		"tspack.manifestBoundary", "tspack.updatePolicy", "tspack.securityPolicy"},
	Dependencies: []string{}, Tools: []string{"vite", "typescript", "@biomejs/biome"},
	Peers: []string{},
	Targets: []string{"app"}, RunTargets: []string{"dev", "build", "preview"},
	Projections: []string{}, HasPack: false},

	generatedCompositionCase{Name: "react-app", Kind: "app",
		Concepts: []string{"react.app", "browser.spa", "vite.app", "typescript.app",
			"tspack.workspace", "tspack.manifestBoundary", "tspack.updatePolicy", "tspack.securityPolicy"},
		Dependencies: []string{"react",
			"react-dom"},
		Tools: []string{"@vitejs/plugin-react", "@types/react", "@types/react-dom", "vite",
			"typescript", "@biomejs/biome"},
		Peers: []string{}, Targets: []string{"app"},
		RunTargets: []string{"dev", "build",
			"preview"}, Projections: []string{},
		HasPack: false},

	generatedCompositionCase{Name: "react-library", Kind: "library",
		Concepts: []string{"react.library", "package.peerDependencies", "package.exports", "tspack.pack",
			"vite.library", "typescript.library", "tspack.workspace", "tspack.manifestBoundary", "tspack.updatePolicy", "tspack.securityPolicy"},
		Dependencies: []string{},
		Tools: []string{"@vitejs/plugin-react", "@types/react", "@types/react-dom", "vite",
			"typescript", "@biomejs/biome"},
		Peers: []string{"react", "react-dom"}, Targets: []string{"library"},
		RunTargets: []string{"build", "build-types", "typecheck"},
		Projections: []string{"package.exports:."}, HasPack: true}}
