package workflow

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const GitHubSetupAction = "yuechen-li-dev/tspack/.github/actions/setup-tspack@v1"

func GitHubPath(workflowIdentity string) string {
	return ".github/workflows/tspack-" + strings.ToLower(workflowIdentity) + ".yml"
}

func ExportGitHub(plan Plan) ([]byte, error) {
	for _, job := range plan.Jobs {
		if job.Platform != "linux" && job.Platform != "currentHost" && job.Platform != "" {
			return nil, fmt.Errorf("TSPACK_WORKFLOW_PROVIDER_UNSUPPORTED: GitHub thin-runner mode cannot execute %s job %s on one Linux runner", job.Platform, job.Identity)
		}
	}

	root := mappingNode()
	appendPair(root, scalar("name"), scalar(plan.Workflow))
	appendPair(root, scalar("on"), githubTriggers(plan.Triggers))
	jobs := mappingNode()
	thinJob := mappingNode()
	appendPair(thinJob, scalar("runs-on"), scalar("ubuntu-latest"))
	secrets := planSecrets(plan)
	if len(secrets) > 0 {
		environment := mappingNode()
		for _, secret := range secrets {
			appendPair(environment, scalar(secret), quotedScalar("${{ secrets."+secret+" }}"))
		}
		appendPair(thinJob, scalar("env"), environment)
	}
	steps := sequenceNode()
	steps.Content = append(steps.Content,
		stepNode("Checkout", "actions/checkout@v4", ""),
		stepNode("Setup TSPack", GitHubSetupAction, ""),
		stepNode("Run TSPack workflow", "", "tspack workflow run "+plan.Workflow+" --ci-provider github"),
	)
	appendPair(thinJob, scalar("steps"), steps)
	appendPair(jobs, scalar("tspack"), thinJob)
	appendPair(root, scalar("jobs"), jobs)

	document := &yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{root}}
	buffer := &bytes.Buffer{}
	buffer.WriteString("# Generated by TSPack. Do not edit manually; manifest.tsx is authoritative.\n")
	encoder := yaml.NewEncoder(buffer)
	encoder.SetIndent(2)
	if err := encoder.Encode(document); err != nil {
		return nil, err
	}
	_ = encoder.Close()
	return buffer.Bytes(), nil
}

func githubTriggers(triggers []Trigger) *yaml.Node {
	mapping := mappingNode()
	ordered := append([]Trigger(nil), triggers...)
	sort.SliceStable(ordered, func(left, right int) bool {
		return triggerOrder(ordered[left].Kind) < triggerOrder(ordered[right].Kind)
	})
	for _, trigger := range ordered {
		key := ""
		switch trigger.Kind {
		case "manual":
			key = "workflow_dispatch"
		case "push":
			key = "push"
		case "pullRequest":
			key = "pull_request"
		}
		value := mappingNode()
		if len(trigger.Branches) > 0 {
			appendPair(value, scalar("branches"), stringSequence(trigger.Branches))
		}
		if len(trigger.Paths) > 0 {
			appendPair(value, scalar("paths"), stringSequence(trigger.Paths))
		}
		appendPair(mapping, scalar(key), value)
	}
	return mapping
}

func planSecrets(plan Plan) []string {
	seen := map[string]struct{}{}
	for _, job := range plan.Jobs {
		for _, environment := range job.Environment {
			if environment.Kind == "secret" {
				seen[environment.Secret] = struct{}{}
			}
		}
		for _, step := range job.Steps {
			for _, environment := range step.Environment {
				if environment.Kind == "secret" {
					seen[environment.Secret] = struct{}{}
				}
			}
		}
	}
	result := make([]string, 0, len(seen))
	for secret := range seen {
		result = append(result, secret)
	}
	sort.Strings(result)
	return result
}

func triggerOrder(kind string) int {
	switch kind {
	case "manual":
		return 0
	case "push":
		return 1
	case "pullRequest":
		return 2
	default:
		return 3
	}
}

func stepNode(name string, uses string, run string) *yaml.Node {
	step := mappingNode()
	appendPair(step, scalar("name"), scalar(name))
	if uses != "" {
		appendPair(step, scalar("uses"), scalar(uses))
	}
	if run != "" {
		appendPair(step, scalar("run"), scalar(run))
	}
	return step
}

func stringSequence(values []string) *yaml.Node {
	sequence := sequenceNode()
	for _, value := range values {
		sequence.Content = append(sequence.Content, scalar(value))
	}
	return sequence
}

func appendPair(mapping *yaml.Node, key *yaml.Node, value *yaml.Node) {
	mapping.Content = append(mapping.Content, key, value)
}

func mappingNode() *yaml.Node {
	return &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
}

func sequenceNode() *yaml.Node {
	return &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
}

func scalar(value string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: value}
}

func quotedScalar(value string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: value, Style: yaml.DoubleQuotedStyle}
}
