package cli

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/yuechen-li-dev/tspack/internal/diag"
)

func TestMigrateMissingPackageJSONDiagnostic(t *testing.T) {
	root := t.TempDir()
	cfg, diags := parseMigrateArgs([]string{"migrate", "--root", root})
	if len(diags) != 0 {
		t.Fatalf("unexpected parse diagnostics: %#v", diags)
	}
	_, diagnostic := buildMigrationDraft(cfg)
	if diagnostic == nil {
		t.Fatalf("expected missing package.json diagnostic")
	}
	if diagnostic.Code != "TSPACK_MIGRATE_PACKAGE_JSON_MISSING" {
		t.Fatalf("unexpected diagnostic code: %s", diagnostic.Code)
	}
	if !strings.Contains(strings.Join(diagnostic.Details, "\n"), filepath.Join(root, "package.json")) {
		t.Fatalf("diagnostic details should include package.json path: %#v", diagnostic.Details)
	}
}

func TestMigrateInvalidPackageJSONDiagnostic(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "package.json"), []byte(`{"name":`), 0o644); err != nil {
		t.Fatal(err)
	}
	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root})
	_, diagnostic := buildMigrationDraft(cfg)
	if diagnostic == nil {
		t.Fatalf("expected invalid package.json diagnostic")
	}
	if diagnostic.Code != "TSPACK_MIGRATE_PACKAGE_JSON_INVALID" {
		t.Fatalf("unexpected diagnostic code: %s", diagnostic.Code)
	}
}

func TestMigrateMinimalPackageDraftAndReport(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{
  "name": "minimal",
  "version": "0.1.0",
  "license": "MIT"
}`)

	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root})
	draft, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}

	for _, want := range []string{
		`name="minimal"`,
		`version="0.1.0"`,
		`license="MIT"`,
		`kind="library"`,
		`MIGRATION_TODO_TARGETS`,
		`MIGRATION_TODO_PUBLISH`,
		`<Publish`,
	} {
		if !strings.Contains(draft.Manifest, want) {
			t.Fatalf("manifest missing %q:\n%s", want, draft.Manifest)
		}
	}
	if strings.Contains(draft.Manifest, `runtime="nodejs"`) {
		t.Fatalf("migration draft should omit workspace runtime because nodejs is the default:\n%s", draft.Manifest)
	}

	for _, want := range []string{
		"# TSPack Migration Report",
		"## Inputs",
		"## Summary",
		"## Mechanical mappings",
		"## TODOs for human/LLM review",
		"## Scripts not migrated",
		"## Suggested next steps",
	} {
		if !strings.Contains(draft.Report, want) {
			t.Fatalf("report missing %q:\n%s", want, draft.Report)
		}
	}
}

func TestMigrateDryRunWritesNothing(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{"name":"dry","version":"1.0.0"}`)

	cmd := newInProcessCommand("migrate", "--root", root)
	cmd.Dir = repoRootForMigrateTest(t)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("dry-run failed: %v\n%s", err, string(output))
	}
	text := string(output)
	if !strings.Contains(text, "Migration draft planned") || !strings.Contains(text, "Run with --write") {
		t.Fatalf("unexpected dry-run output:\n%s", text)
	}
	assertFileMissing(t, filepath.Join(root, "manifest.migrated.tsx"))
	assertFileMissing(t, filepath.Join(root, "tspack-migration.md"))
}

func TestMigrateWriteForceAndAllOrNothing(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{"name":"writer","version":"1.0.0","dependencies":{"react-dom":"^19"}}`)
	repo := repoRootForMigrateTest(t)

	cmd := newInProcessCommand("migrate", "--root", root, "--write")
	cmd.Dir = repo
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("write failed: %v\n%s", err, string(output))
	}
	manifestPath := filepath.Join(root, "manifest.migrated.tsx")
	reportPath := filepath.Join(root, "tspack-migration.md")
	assertFileContains(t, manifestPath, `reactDom: dep(npm("react-dom", "^19"), { key: "react-dom" })`)
	assertFileContains(t, reportPath, "TSPack Migration Report")

	if err := os.Remove(reportPath); err != nil {
		t.Fatal(err)
	}
	cmd = newInProcessCommand("migrate", "--root", root, "--write")
	cmd.Dir = repo
	output, err = cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("expected collision failure:\n%s", string(output))
	}
	if !strings.Contains(string(output), "TSPACK_MIGRATE_OUTPUT_EXISTS") {
		t.Fatalf("collision output missing diagnostic:\n%s", string(output))
	}
	assertFileMissing(t, reportPath)

	if err := os.WriteFile(manifestPath, []byte("old manifest"), 0o644); err != nil {
		t.Fatal(err)
	}
	cmd = newInProcessCommand("migrate", "--root", root, "--write", "--force")
	cmd.Dir = repo
	output, err = cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("force write failed: %v\n%s", err, string(output))
	}
	assertFileContains(t, manifestPath, "Generated by `tspack migrate`")
	assertFileContains(t, reportPath, "## Suggested next steps")
}

func TestMigrateMetadataKindDependenciesTargetsPublishAndScripts(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{
  "name": "@acme/components",
  "version": "0.2.0",
  "license": "Apache-2.0",
  "exports": {
    ".": { "types": "./dist/index.d.ts", "import": "./dist/index.js" },
    "./react": { "types": "./dist/react/index.d.ts", "default": "./dist/react/index.js" }
  },
  "files": ["dist/**", "README.md"],
  "dependencies": { "@scope/pkg": "^1.0.0", "react": "^19.0.0" },
  "peerDependencies": { "react": "^19.0.0" },
  "peerDependenciesMeta": { "react": { "optional": true } },
  "devDependencies": { "typescript": "^5.9.0", "unknown-tool": "1.0.0" },
  "optionalDependencies": { "fsevents": "^2.3.0" },
  "scripts": { "dev": "vite", "postinstall": "node install.js" }
}`)

	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root})
	draft, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}

	manifest := draft.Manifest
	for _, want := range []string{
		`name="@acme/components"`,
		`version="0.2.0"`,
		`license="Apache-2.0"`,
		`kind="library"`,
		`react: peer(npm("react", "^19.0.0"), { optional: true })`,
		`scopePkg: dep(npm("@scope/pkg", "^1.0.0"), { key: "@scope/pkg" })`,
		`fsevents: dep(npm("fsevents", "^2.3.0"))`,
		`typescript: tool(npm("typescript", "^5.9.0"))`,
		`unknownTool: tool(npm("unknown-tool", "1.0.0"), { key: "unknown-tool" })`,
		`name: "core"`,
		`name: "react"`,
		`include={["dist/**", "README.md"]}`,
		`MIGRATION_TODO_RUN_TARGETS`,
		`MIGRATION_TODO_SECURITY`,
	} {
		if !strings.Contains(manifest, want) {
			t.Fatalf("manifest missing %q:\n%s", want, manifest)
		}
	}
	if strings.Contains(manifest, `react: dep(`) {
		t.Fatalf("duplicate dependency should prefer peer classification:\n%s", manifest)
	}
	for _, want := range []string{"Duplicate dependency/peer declarations preferred peer classification", "`dev`: `vite`", "`postinstall`: `node install.js`"} {
		if !strings.Contains(draft.Report, want) {
			t.Fatalf("report missing %q:\n%s", want, draft.Report)
		}
	}
}

func TestMigratePrivateAppInferenceAndConservativePublish(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{"name":"app","version":"1.0.0","private":true}`)
	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root})
	draft, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}
	for _, want := range []string{`kind="app"`, `name: "app"`, `runtime: "dist/main.js"`, `types: ""`, `include={["dist/**", "README.md", "LICENSE"]}`} {
		if !strings.Contains(draft.Manifest, want) {
			t.Fatalf("app manifest missing %q:\n%s", want, draft.Manifest)
		}
	}
}

func TestMigrateIdentifierCollisionsAreReported(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{
  "name":"collide",
  "version":"1.0.0",
  "dependencies": {
    "@scope/pkg": "1.0.0",
    "scope-pkg": "2.0.0"
  }
}`)
	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root})
	draft, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}
	if !strings.Contains(draft.Manifest, "scopePkg2") {
		t.Fatalf("expected deterministic suffixed identifier:\n%s", draft.Manifest)
	}
	if !strings.Contains(draft.Report, "Identifier collisions") {
		t.Fatalf("expected collision report:\n%s", draft.Report)
	}
}

func TestMigrateReportStableAcrossRepeatedRuns(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{"name":"stable","version":"1.0.0","devDependencies":{"z":"1","a":"1"},"scripts":{"test":"echo test","build":"echo build"}}`)
	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root})
	first, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}
	second, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}
	if first.Manifest != second.Manifest {
		t.Fatalf("manifest is not stable")
	}
	if first.Report != second.Report {
		t.Fatalf("report is not stable")
	}
}

func TestMigratePackageLockEvidenceReport(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{
  "name": "locked",
  "version": "1.0.0",
  "dependencies": { "react": "^18.3.1" },
  "devDependencies": { "vite": "^5.0.0" },
  "peerDependencies": { "@types/react": "^18.3.0" }
}`)
	writePackageLock(t, root, `{
  "name": "locked",
  "lockfileVersion": 3,
  "packages": {
    "": {
      "name": "locked",
      "dependencies": { "react": "^18.3.1", "left-pad": "^1.3.0" },
      "devDependencies": { "vite": "^5.0.0" },
      "peerDependencies": { "@types/react": "^18.3.0" }
    },
    "node_modules/react": {
      "version": "18.3.1",
      "resolved": "https://registry.npmjs.org/react/-/react-18.3.1.tgz",
      "integrity": "sha512-reactintegritylongvalue",
      "peerDependencies": { "loose-envify": "^1.1.0" }
    },
    "node_modules/vite": {
      "version": "5.4.0",
      "resolved": "https://registry.npmjs.org/vite/-/vite-5.4.0.tgz",
      "integrity": "sha512-viteintegritylongvalue",
      "dependencies": { "esbuild": "^0.21.0" },
      "bin": { "vite": "bin/openChrome.applescript" }
    },
    "node_modules/esbuild": {
      "version": "0.21.5",
      "dependencies": { "@esbuild/linux-x64": "0.21.5" },
      "bin": { "esbuild": "bin/esbuild" },
      "scripts": { "postinstall": "node install.js" }
    },
    "node_modules/@esbuild/linux-x64": {
      "version": "0.21.5",
      "os": ["linux"],
      "cpu": ["x64"]
    },
    "node_modules/@types/react": {
      "version": "18.3.3"
    },
    "node_modules/a/node_modules/react": {
      "name": "react",
      "version": "17.0.2"
    }
  }
}`)

	cfg, diags := parseMigrateArgs([]string{"migrate", "--root", root})
	if len(diags) != 0 {
		t.Fatalf("unexpected parse diagnostics: %#v", diags)
	}
	draft, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}

	for _, want := range []string{
		"## Lockfile evidence",
		"lockfileVersion: `3`",
		"| `react` | `^18.3.1` | `18.3.1` | `dep` |",
		"| `vite` | `^5.0.0` | `5.4.0` | `tool` |",
		"### Lifecycle capabilities",
		"`esbuild@0.21.5` | `postinstall` | `node install.js`",
		"### Binary packages",
		"`vite@5.4.0`",
		"### Peer evidence",
		"`react@18.3.1`",
		"### Platform/native package evidence",
		"`@esbuild/linux-x64@0.21.5`",
		"duplicate locked versions for `react`",
		"lock root dependencies not declared in package.json fields consumed by migrate: `left-pad`",
		"lock evidence includes type packages needing type-policy review: `@types/react`",
		"Lock evidence detected 1 dependency lifecycle script capabilities",
	} {
		if !strings.Contains(draft.Report, want) {
			t.Fatalf("report missing %q:\n%s", want, draft.Report)
		}
	}
	if strings.Contains(draft.Manifest, "node install.js") {
		t.Fatalf("manifest should not include detailed lock script commands:\n%s", draft.Manifest)
	}
}

func TestMigrateImplicitPackageLockInvalidWarnsAndContinues(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{"name":"badlock","version":"1.0.0"}`)
	writePackageLock(t, root, `{"lockfileVersion":3,`)

	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root})
	draft, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("implicit invalid lock should not fail: %#v", diagnostic)
	}
	if len(draft.Diagnostics) != 1 || draft.Diagnostics[0].Code != "TSPACK_MIGRATE_PACKAGE_LOCK_INVALID" {
		t.Fatalf("expected warning diagnostic: %#v", draft.Diagnostics)
	}
	if !strings.Contains(draft.Report, "lock evidence: invalid; ignored") {
		t.Fatalf("report should mention invalid ignored lock:\n%s", draft.Report)
	}
}

func TestMigrateExplicitPackageLockMissingAndInvalidFail(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{"name":"explicit","version":"1.0.0"}`)

	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root, "--package-lock", "missing-lock.json"})
	_, diagnostic := buildMigrationDraft(cfg)
	if diagnostic == nil || diagnostic.Code != "TSPACK_MIGRATE_PACKAGE_LOCK_MISSING" {
		t.Fatalf("expected explicit missing lock diagnostic: %#v", diagnostic)
	}

	badPath := filepath.Join(root, "bad-lock.json")
	if err := os.WriteFile(badPath, []byte(`{"lockfileVersion":3,`), 0o644); err != nil {
		t.Fatal(err)
	}
	cfg, _ = parseMigrateArgs([]string{"migrate", "--root", root, "--package-lock", badPath})
	_, diagnostic = buildMigrationDraft(cfg)
	if diagnostic == nil || diagnostic.Code != "TSPACK_MIGRATE_PACKAGE_LOCK_INVALID" {
		t.Fatalf("expected explicit invalid lock diagnostic: %#v", diagnostic)
	}
}

func TestMigrateNoLockEvidenceSkipsExistingLock(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{"name":"skiplock","version":"1.0.0","dependencies":{"react":"^18"}}`)
	writePackageLock(t, root, `{"lockfileVersion":3,"packages":{"node_modules/react":{"version":"18.3.1"}}}`)

	cfg, diags := parseMigrateArgs([]string{"migrate", "--root", root, "--no-lock-evidence"})
	if len(diags) != 0 {
		t.Fatalf("unexpected diagnostics: %#v", diags)
	}
	draft, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}
	if !strings.Contains(draft.Report, "lock evidence: skipped by `--no-lock-evidence`") {
		t.Fatalf("report should mention skipped lock evidence:\n%s", draft.Report)
	}

	_, diags = parseMigrateArgs([]string{"migrate", "--root", root, "--package-lock", "package-lock.json", "--no-lock-evidence"})
	if len(diags) != 1 || diags[0].Code != "TSPACK_MIGRATE_INVALID_ARGS" {
		t.Fatalf("expected invalid args diagnostic: %#v", diags)
	}
}

func TestMigrateWriteWithLockEvidenceDoesNotWriteTsLock(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{"name":"writelock","version":"1.0.0","dependencies":{"react":"^18"}}`)
	writePackageLock(t, root, `{"lockfileVersion":3,"packages":{"node_modules/react":{"version":"18.3.1"}}}`)
	repo := repoRootForMigrateTest(t)

	cmd := newInProcessCommand("migrate", "--root", root, "--write")
	cmd.Dir = repo
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("write with lock failed: %v\n%s", err, string(output))
	}
	assertFileContains(t, filepath.Join(root, "tspack-migration.md"), "## Lockfile evidence")
	assertFileContains(t, filepath.Join(root, "tspack-migration.md"), "| `react` | `^18` | `18.3.1` | `dep` |")
	assertFileMissing(t, filepath.Join(root, "ts-lock.toml"))
}

func TestMigrateSourceImportEvidence(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{
  "name": "source-evidence",
  "version": "1.0.0",
  "dependencies": { "clsx": "^2.0.0", "zod": "^3.0.0" },
  "peerDependencies": { "react": "^19.0.0" },
  "devDependencies": { "lodash": "^4.17.21" }
}`)
	writeTestFile(t, filepath.Join(root, "src", "index.ts"), `import clsx from "clsx";
import type { ZodType } from "zod";
import { debounce } from "lodash";
import "./local";
import("left-pad");
export { jsx } from "react/jsx-runtime";
`)
	writeTestFile(t, filepath.Join(root, "src", "Button.tsx"), `import React, { type ReactNode } from "react";
import scoped from "@scope/pkg/subpath";
import fs from "node:fs";
import path from "path";
void scoped;
void fs;
void path;
export type { ButtonHTMLAttributes } from "react";
`)
	writeTestFile(t, filepath.Join(root, "dist", "ignored.js"), `import ignored from "ignored-dist"; void ignored;`)
	writeTestFile(t, filepath.Join(root, "node_modules", "ignored", "index.js"), `import ignored from "ignored-node-modules"; void ignored;`)

	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root})
	draft, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}

	for _, want := range []string{
		"## Source import evidence",
		"- status: enabled",
		"- roots scanned: `src`",
		"| `clsx` | `runtime` | `dependency` | `src/index.ts` | `clsx` |",
		"| `react` | `runtime+type+mixed` | `peerDependency` |",
		"| `lodash` | `runtime` | `devDependency` | `src/index.ts` | `lodash` |",
		"| `zod` | `type` | `dependency` | `src/index.ts` | `zod` |",
		"| `left-pad` | `runtime+dynamic` | `missing` | `src/index.ts` | `left-pad` |",
		"| `@scope/pkg` | `runtime` | `missing` | `src/Button.tsx` | `@scope/pkg/subpath` |",
		"runtime imports declared only as devDependencies: `lodash`",
		"packages observed only through type-only imports: `zod`",
		"imported packages missing from direct package.json declarations: `@scope/pkg`, `left-pad`",
		"Node builtin imports observed: `fs` (1), `path` (1)",
	} {
		if !strings.Contains(draft.Report, want) {
			t.Fatalf("report missing %q:\n%s", want, draft.Report)
		}
	}
	for _, unwanted := range []string{"ignored-dist", "ignored-node-modules", "./local"} {
		if strings.Contains(draft.Report, unwanted) {
			t.Fatalf("report should not contain %q:\n%s", unwanted, draft.Report)
		}
	}
	for _, want := range []string{
		"Source scan observed undeclared external imports: `@scope/pkg`, `left-pad`",
		"Source scan found runtime imports while package.json declares this as a devDependency.",
		"Source evidence: runtime imports found in src/index.ts.",
		"MIGRATION_TODO_TYPES: Source scan only found type-only imports; verify type dependency intent.",
	} {
		if !strings.Contains(draft.Manifest, want) {
			t.Fatalf("manifest missing %q:\n%s", want, draft.Manifest)
		}
	}
}

func TestMigrateNoSourceScanSkipsSourceEvidence(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{"name":"skip-source","version":"1.0.0","dependencies":{"clsx":"^2"}}`)
	writeTestFile(t, filepath.Join(root, "src", "index.ts"), `import clsx from "clsx";`)

	cfg, diags := parseMigrateArgs([]string{"migrate", "--root", root, "--no-source-scan"})
	if len(diags) != 0 {
		t.Fatalf("unexpected diagnostics: %#v", diags)
	}
	draft, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}
	if !strings.Contains(draft.Report, "- source scan: skipped by `--no-source-scan`") {
		t.Fatalf("report should mention skipped source scan:\n%s", draft.Report)
	}
	if strings.Contains(draft.Report, "| `clsx` | `runtime`") {
		t.Fatalf("report should not include observed source imports when skipped:\n%s", draft.Report)
	}

	_, diags = parseMigrateArgs([]string{"migrate", "--root", root, "--scan-source", "--no-source-scan"})
	if len(diags) != 1 || diags[0].Code != "TSPACK_MIGRATE_INVALID_ARGS" {
		t.Fatalf("expected invalid args diagnostic: %#v", diags)
	}
}

func TestMigrateSourceScanStableReport(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{"name":"stable-source","version":"1.0.0","dependencies":{"a":"1.0.0","b":"1.0.0"}}`)
	writeTestFile(t, filepath.Join(root, "src", "b.ts"), `import b from "b"; void b;`)
	writeTestFile(t, filepath.Join(root, "src", "a.ts"), `import a from "a"; void a;`)

	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root})
	first, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}
	second, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}
	if first.Report != second.Report {
		t.Fatalf("source scan report should be stable\nfirst:\n%s\nsecond:\n%s", first.Report, second.Report)
	}
}

func writePackageJSON(t *testing.T, root string, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(root, "package.json"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func writePackageLock(t *testing.T, root string, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(root, "package-lock.json"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func writeTestFile(t *testing.T, path string, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func assertFileMissing(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); err == nil {
		t.Fatalf("expected file to be missing: %s", path)
	} else if !os.IsNotExist(err) {
		t.Fatalf("unexpected stat error for %s: %v", path, err)
	}
}

func assertFileContains(t *testing.T, path string, want string) {
	t.Helper()
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(content), want) {
		t.Fatalf("%s missing %q:\n%s", path, want, string(content))
	}
}

func repoRootForMigrateTest(t *testing.T) string {
	t.Helper()
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	return filepath.Clean(filepath.Join(wd, "..", ".."))
}

func TestMigrateScriptClassificationAndRunTargetSuggestions(t *testing.T) {
	cases := []struct {
		name       string
		scriptName string
		command    string
		category   string
		confidence string
		url        string
		ready      string
	}{
		{
			name:       "vite dev",
			scriptName: "dev",
			command:    "vite",
			category:   "runtime-target-candidate",
			confidence: "high",
			url:        "http://127.0.0.1:5173",
			ready:      "http /",
		},
		{
			name:       "next dev",
			scriptName: "dev",
			command:    "next dev",
			category:   "runtime-target-candidate",
			confidence: "high",
			url:        "http://127.0.0.1:3000",
			ready:      "http /",
		},
		{
			name:       "storybook",
			scriptName: "storybook",
			command:    "storybook dev -p 6006",
			category:   "runtime-target-candidate",
			confidence: "high",
			url:        "http://127.0.0.1:6006",
			ready:      "http /",
		},
		{
			name:       "node start",
			scriptName: "start",
			command:    "node server.js",
			category:   "runtime-target-candidate",
			confidence: "high",
			ready:      "TODO",
		},
		{
			name:       "custom port",
			scriptName: "dev",
			command:    "vite --port 4000",
			category:   "runtime-target-candidate",
			confidence: "high",
			url:        "http://127.0.0.1:4000",
			ready:      "http /",
		},
		{name: "build", scriptName: "build", command: "vite build", category: "build", confidence: "high"},
		{name: "test", scriptName: "test", command: "vitest", category: "test", confidence: "high"},
		{name: "lint", scriptName: "lint", command: "biome lint .", category: "lint", confidence: "high"},
		{name: "format", scriptName: "format", command: "biome format --write .", category: "format", confidence: "high"},
		{name: "lifecycle", scriptName: "postinstall", command: "node install.js", category: "lifecycle", confidence: "high"},
		{name: "clean", scriptName: "clean", command: "rimraf dist", category: "maintenance", confidence: "medium"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			analysis := analyzePackageScript(tc.scriptName, tc.command)
			if analysis.Category != tc.category {
				t.Fatalf("category = %q, want %q", analysis.Category, tc.category)
			}
			if analysis.Confidence != tc.confidence {
				t.Fatalf("confidence = %q, want %q", analysis.Confidence, tc.confidence)
			}
			if tc.category == "runtime-target-candidate" {
				if analysis.Suggestion == nil {
					t.Fatalf("missing suggestion")
				}
				if len(analysis.Suggestion.Command) == 0 {
					t.Fatalf("missing suggestion command")
				}
				if analysis.Suggestion.URL != tc.url {
					t.Fatalf("url = %q, want %q", analysis.Suggestion.URL, tc.url)
				}
				if analysis.Suggestion.Ready != tc.ready {
					t.Fatalf("ready = %q, want %q", analysis.Suggestion.Ready, tc.ready)
				}
			}
		})
	}
}

func TestMigrateScriptComplexShellAndEnvReview(t *testing.T) {
	cases := []struct {
		name    string
		command string
		want    string
	}{
		{name: "shell composite", command: "vite && node foo.js", want: "shell-composite"},
		{name: "env prefix", command: "PORT=3001 vite", want: "environment prefix"},
		{name: "cross env", command: "cross-env PORT=3001 vite", want: "environment prefix"},
		{name: "redirection", command: "vite > out.log", want: "shell-composite"},
		{name: "backticks", command: "echo `date`", want: "shell-composite"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			analysis := analyzePackageScript("dev", tc.command)
			if !analysis.NeedsReview {
				t.Fatalf("expected review for %q", tc.command)
			}
			if !strings.Contains(strings.Join(analysis.ReviewNotes, "; "), tc.want) {
				t.Fatalf("notes missing %q: %#v", tc.want, analysis.ReviewNotes)
			}
		})
	}
}

func TestMigrateScriptReportManifestAndSafety(t *testing.T) {
	root := t.TempDir()
	marker := filepath.Join(root, "marker")
	writePackageJSON(t, root, `{
  "name": "scripts-app",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "vite --host 127.0.0.1",
    "build": "vite build",
    "test": "vitest",
    "lint": "eslint .",
    "format": "prettier --write .",
    "postinstall": "node -e \"require('fs').writeFileSync('marker','bad')\"",
    "weird": "echo $(date)"
  }
}`)
	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root})
	draft, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}

	for _, want := range []string{
		"## Scripts and RunTarget suggestions",
		"### Suggested RunTarget candidates",
		"| `dev` | `dev` | `high` | `[\"vite\", \"--host\", \"127.0.0.1\"]`",
		"### Non-RunTarget scripts",
		"`build` (`build`)",
		"`test` (`test`)",
		"`lint` (`lint`)",
		"`format` (`format`)",
		"### Shell/Env review",
		"`weird`",
		"## Security",
		"postinstall",
	} {
		if !strings.Contains(draft.Report, want) {
			t.Fatalf("report missing %q:\n%s", want, draft.Report)
		}
	}
	if !strings.Contains(draft.Manifest, "MIGRATION_TODO_RUN_TARGETS") {
		t.Fatalf("manifest missing run target TODO:\n%s", draft.Manifest)
	}
	if strings.Contains(draft.Manifest, "<RunTargets") {
		t.Fatalf("manifest should not include active RunTargets:\n%s", draft.Manifest)
	}
	assertFileMissing(t, marker)
}

func migrateValidationFrontendEnv(t *testing.T) string {
	t.Helper()

	frontendDir := t.TempDir()
	cliPath := filepath.Join(frontendDir, "cli.js")
	stub := `const fs = require('fs');
const manifestPath = process.argv[2];
const manifest = fs.readFileSync(manifestPath, 'utf8');
const nameMatch = manifest.match(/name=\"([^\"]+)\"/);
const versionMatch = manifest.match(/version=\"([^\"]+)\"/);
const kindMatch = manifest.match(/kind=\"([^\"]+)\"/);
const packageName = nameMatch ? nameMatch[1] : 'migrated';
const packageVersion = versionMatch ? versionMatch[1] : '1.0.0';
const packageKind = kindMatch ? kindMatch[1] : 'library';
const ir = {
  format: 1,
  workspace: { name: packageName },
  packages: [
    {
      name: packageName,
      version: packageVersion,
      kind: packageKind,
      dependencies: [],
      targets: [],
      tools: [],
      boundaries: [],
      publish: { include: ['dist/**'], exclude: [] },
      policies: {}
    }
  ]
};
process.stdout.write(JSON.stringify({ ok: true, ir, diagnostics: [] }));
`
	if err := os.WriteFile(cliPath, []byte(stub), 0o755); err != nil {
		t.Fatalf("write migrate frontend stub: %v", err)
	}
	return "TSPACK_MANIFEST_FRONTEND=" + cliPath
}

func migrateCommandWithValidationFrontend(t *testing.T, args ...string) *exec.Cmd {
	t.Helper()

	cmd := exec.Command("go", args...)
	cmd.Dir = repoRootForMigrateTest(t)
	cmd.Env = append(os.Environ(), migrateValidationFrontendEnv(t))
	return cmd
}

func TestMigrateCheckDryRunSuccessWritesNothing(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{
  "name":"check-dry",
  "version":"1.0.0",
  "dependencies":{"react":"^19.0.0"},
  "scripts":{"dev":"vite","postinstall":"node postinstall.js"}
}`)

	cmd := migrateCommandWithValidationFrontend(t, "run", "./cmd/tspack", "migrate", "--root", root, "--check")
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("check dry-run failed: %v\n%s", err, string(output))
	}
	text := string(output)
	for _, want := range []string{"Validation:", "manifest frontend: passed", "manifest IR: passed", "result: structurally valid draft", "TODOs:"} {
		if !strings.Contains(text, want) {
			t.Fatalf("check output missing %q:\n%s", want, text)
		}
	}
	assertFileMissing(t, filepath.Join(root, "manifest.migrated.tsx"))
	assertFileMissing(t, filepath.Join(root, "tspack-migration.md"))
	assertFileMissing(t, filepath.Join(root, "ts-lock.toml"))
	assertFileMissing(t, filepath.Join(root, "script-marker"))
}

func TestMigrateCheckWriteSuccessReportValidation(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{"name":"check-write","version":"1.0.0","devDependencies":{"typescript":"^5.9.0"}}`)

	cmd := migrateCommandWithValidationFrontend(t, "run", "./cmd/tspack", "migrate", "--root", root, "--write", "--check")
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("check write failed: %v\n%s", err, string(output))
	}
	text := string(output)
	if !strings.Contains(text, "Validation:") || !strings.Contains(text, "result: structurally valid draft") {
		t.Fatalf("write output missing validation summary:\n%s", text)
	}
	assertFileContains(t, filepath.Join(root, "manifest.migrated.tsx"), "Generated by `tspack migrate`")
	assertFileContains(t, filepath.Join(root, "tspack-migration.md"), "## Validation")
	assertFileContains(t, filepath.Join(root, "tspack-migration.md"), "Status: passed")
	assertFileContains(t, filepath.Join(root, "tspack-migration.md"), "- Remaining TODOs:")
}

func TestMigrateCheckFailureBlocksWrite(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{"name":"bad check","version":"1.0.0"}`)

	cmd := migrateCommandWithValidationFrontend(t, "run", "./cmd/tspack", "migrate", "--root", root, "--write", "--check")
	output, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("expected validation failure:\n%s", string(output))
	}
	text := string(output)
	if !strings.Contains(text, "TSPACK_MIGRATE_GENERATED_IR_INVALID") || !strings.Contains(text, "TSPACK_IR_INVALID_PACKAGE_NAME") || !strings.Contains(text, "no files were written") {
		t.Fatalf("validation failure output missing diagnostic:\n%s", text)
	}
	assertFileMissing(t, filepath.Join(root, "manifest.migrated.tsx"))
	assertFileMissing(t, filepath.Join(root, "tspack-migration.md"))
}

func TestMigrateReportValidationNotRunWithoutCheck(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{"name":"not-run","version":"1.0.0"}`)

	cmd := newInProcessCommand("migrate", "--root", root, "--write")
	cmd.Dir = repoRootForMigrateTest(t)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("write failed: %v\n%s", err, string(output))
	}
	assertFileContains(t, filepath.Join(root, "tspack-migration.md"), "## Validation")
	assertFileContains(t, filepath.Join(root, "tspack-migration.md"), "Status: not run")
	assertFileContains(t, filepath.Join(root, "tspack-migration.md"), "tspack migrate --check")
}

func TestMigrateCheckOutputCollisionFailsBeforeValidation(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{"name":"collision","version":"1.0.0"}`)
	if err := os.WriteFile(filepath.Join(root, "manifest.migrated.tsx"), []byte("old"), 0o644); err != nil {
		t.Fatal(err)
	}

	cmd := migrateCommandWithValidationFrontend(t, "run", "./cmd/tspack", "migrate", "--root", root, "--write", "--check")
	output, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("expected collision failure:\n%s", string(output))
	}
	text := string(output)
	if !strings.Contains(text, "TSPACK_MIGRATE_OUTPUT_EXISTS") || strings.Contains(text, "Validation:") {
		t.Fatalf("collision should fail before validation:\n%s", text)
	}
	assertFileContains(t, filepath.Join(root, "manifest.migrated.tsx"), "old")
}

func TestMigratePhase8aScopedFixtureCheckRerun(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{
  "name": "@phase8a/scoped-migrate",
  "version": "0.1.0",
  "license": "MIT",
  "devDependencies": {
    "@biomejs/biome": "^1.9.4",
    "@types/react": "^18.2.0",
    "react-dom": "^18.3.1",
    "typescript": "^5.0.0"
  },
  "peerDependencies": {
    "react-dom": "^18.3.1"
  },
  "peerDependenciesMeta": {
    "react-dom": {
      "optional": true
    }
  },
  "main": "./dist/index.js",
  "types": "./dist/index.d.ts",
  "files": ["dist", "README.md", "LICENSE"]
}`)

	checkCmd := migrateCommandWithValidationFrontend(t, "run", "./cmd/tspack", "migrate", "--check", "--root", root)
	checkOutput, err := checkCmd.CombinedOutput()
	if err != nil {
		t.Fatalf("phase 8a migrate --check failed: %v\n%s", err, string(checkOutput))
	}
	checkText := string(checkOutput)
	for _, forbidden := range []string{"TSPACK_IR_UNKNOWN_DEPENDENCY_REF", "TSPACK_MIGRATE_GENERATED_IR_INVALID"} {
		if strings.Contains(checkText, forbidden) {
			t.Fatalf("migrate --check output contained %s:\n%s", forbidden, checkText)
		}
	}

	writeCmd := migrateCommandWithValidationFrontend(t, "run", "./cmd/tspack", "migrate", "--write", "--check", "--root", root)
	writeOutput, err := writeCmd.CombinedOutput()
	if err != nil {
		t.Fatalf("phase 8a migrate --write --check failed: %v\n%s", err, string(writeOutput))
	}
	writeText := string(writeOutput)
	for _, forbidden := range []string{"TSPACK_IR_UNKNOWN_DEPENDENCY_REF", "TSPACK_MIGRATE_GENERATED_IR_INVALID"} {
		if strings.Contains(writeText, forbidden) {
			t.Fatalf("migrate --write --check output contained %s:\n%s", forbidden, writeText)
		}
	}

	manifestPath := filepath.Join(root, "manifest.migrated.tsx")
	for _, want := range []string{
		`biomejsBiome: tool(npm("@biomejs/biome", "^1.9.4"), { key: "@biomejs/biome" })`,
		`typesReact: tool(npm("@types/react", "^18.2.0"), { key: "@types/react" })`,
		`reactDom: peer(npm("react-dom", "^18.3.1"), { key: "react-dom", optional: true })`,
		`peers: ["react-dom"]`,
		`runtime: "dist/index.js"`,
		`types: "dist/index.d.ts"`,
	} {
		assertFileContains(t, manifestPath, want)
	}
}

func TestMigrateExplicitKeysForGeneratedAliases(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{
  "name":"alias-keys",
  "version":"1.0.0",
  "devDependencies": {
    "@biomejs/biome": "^1.9.4",
    "@types/react": "^18.2.0",
    "typescript": "^5.0.0"
  },
  "peerDependencies": {
    "react-dom": "^18.3.1"
  },
  "peerDependenciesMeta": {
    "react-dom": { "optional": true }
  }
}`)

	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root})
	draft, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}

	for _, want := range []string{
		`biomejsBiome: tool(npm("@biomejs/biome", "^1.9.4"), { key: "@biomejs/biome" })`,
		`typesReact: tool(npm("@types/react", "^18.2.0"), { key: "@types/react" })`,
		`reactDom: peer(npm("react-dom", "^18.3.1"), { key: "react-dom", optional: true })`,
		`typescript: tool(npm("typescript", "^5.0.0"))`,
		`peers: ["react-dom"]`,
		`<Tools values={[deps.biomejsBiome, deps.typesReact, deps.typescript]} />`,
	} {
		if !strings.Contains(draft.Manifest, want) {
			t.Fatalf("manifest missing %q:\n%s", want, draft.Manifest)
		}
	}
	if strings.Contains(draft.Manifest, `typescript: tool(npm("typescript", "^5.0.0"), { key:`) {
		t.Fatalf("manifest should not emit unnecessary key for matching identifier:\n%s", draft.Manifest)
	}
}

func TestMigrateTargetDependencyRefsUsePackageIdentities(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{
  "name":"target-refs",
  "version":"1.0.0",
  "dependencies": { "react-dom": "^18.3.1", "@scope/pkg": "^1.0.0" },
  "peerDependencies": { "@types/react": "^18.2.0" }
}`)

	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root})
	draft, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}

	for _, want := range []string{
		`scopePkg: dep(npm("@scope/pkg", "^1.0.0"), { key: "@scope/pkg" })`,
		`reactDom: dep(npm("react-dom", "^18.3.1"), { key: "react-dom" })`,
		`typesReact: peer(npm("@types/react", "^18.2.0"), { key: "@types/react" })`,
		`deps: ["@scope/pkg", "react-dom"]`,
		`peers: ["@types/react"]`,
	} {
		if !strings.Contains(draft.Manifest, want) {
			t.Fatalf("manifest missing %q:\n%s", want, draft.Manifest)
		}
	}
	if strings.Contains(draft.Manifest, `deps: [deps.`) || strings.Contains(draft.Manifest, `peers: [deps.`) {
		t.Fatalf("target dependency refs should use string identities:\n%s", draft.Manifest)
	}
}

func TestMigrateCanonicalizesGeneratedTargetPaths(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{
  "name":"paths",
  "version":"1.0.0",
  "main":"./dist/index.js",
  "types":"./dist/index.d.ts"
}`)

	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root})
	draft, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}
	for _, want := range []string{`runtime: "dist/index.js"`, `types: "dist/index.d.ts"`} {
		if !strings.Contains(draft.Manifest, want) {
			t.Fatalf("manifest missing %q:\n%s", want, draft.Manifest)
		}
	}
	if strings.Contains(draft.Manifest, `runtime: "./dist/index.js"`) || strings.Contains(draft.Manifest, `types: "./dist/index.d.ts"`) {
		t.Fatalf("manifest should strip leading ./ from generated runtime/types paths:\n%s", draft.Manifest)
	}
}

func TestMigrateCanonicalizesExportTargetPaths(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{
  "name":"export-paths",
  "version":"1.0.0",
  "exports": {
    ".": { "types": "./dist/index.d.ts", "default": "./dist/index.js" }
  }
}`)

	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root})
	draft, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}
	for _, want := range []string{`runtime: "dist/index.js"`, `types: "dist/index.d.ts"`} {
		if !strings.Contains(draft.Manifest, want) {
			t.Fatalf("manifest missing %q:\n%s", want, draft.Manifest)
		}
	}
}

func TestMigrateDoesNotCanonicalizeParentTargetPaths(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{
  "name":"parent-paths",
  "version":"1.0.0",
  "main":"../dist/index.js",
  "types":"../dist/index.d.ts"
}`)

	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root})
	draft, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}
	for _, want := range []string{`runtime: "../dist/index.js"`, `types: "../dist/index.d.ts"`} {
		if !strings.Contains(draft.Manifest, want) {
			t.Fatalf("manifest missing %q:\n%s", want, draft.Manifest)
		}
	}
}

func TestMigrateInvalidIRDiagnosticClarifiesTodos(t *testing.T) {
	result := migrationValidationResult{TempPath: "/tmp/manifest.tsx", RemainingTodos: 3}
	diagnostics := []diag.Diagnostic{{
		Code:     "TSPACK_IR_UNKNOWN_DEPENDENCY_REF",
		Severity: diag.SeverityError,
		Message:  "unknown dependency ref",
	}}

	diagnostic := migrationIRInvalidDiagnostic(result, diagnostics)
	details := strings.Join(diagnostic.Details, "\n")
	fixes := strings.Join(diagnostic.Fixes, "\n")
	for _, want := range []string{
		"remainingTodos: 3",
		"todosAreErrors: false",
		"alias/key mismatch",
		"TSPACK_IR_UNKNOWN_DEPENDENCY_REF",
	} {
		if !strings.Contains(details, want) {
			t.Fatalf("diagnostic details missing %q: %#v", want, diagnostic.Details)
		}
	}
	if !strings.Contains(fixes, "MIGRATION_TODO_* comments do not fail validation") {
		t.Fatalf("diagnostic fixes should clarify TODO behavior: %#v", diagnostic.Fixes)
	}
}
