// Command generate-concepts renders TSPack's Oct-derived built-in concept
// registry and its coordinated resolver-expectation table.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"os"

	experimental "github.com/yuechen-li-dev/oct/experimental/octgen"
)

const generatedHeader = "// Code generated by OctGen. DO NOT EDIT.\n// OctGen model: tspack-concepts.v1 (experimental).\n"

type dependency struct {
	Name   string
	Range  string
	Source string
}

type target struct {
	Name    string
	Export  string
	Entry   string
	Runtime string
	Types   string
}

type runTarget struct {
	Name    string
	Command string
}

type policy struct {
	Subject string
	Action  string
	Range   string
}

type projection struct {
	Object string
	Key    string
	Value  string
}

type concept struct {
	Name             string
	Description      string
	Provides         []string
	Requires         []string
	Conflicts        []string
	CompatibleKinds  []string
	Dependencies     []dependency
	Tools            []dependency
	Peers            []dependency
	Targets          []target
	RunTargets       []runTarget
	UpdatePolicy     []policy
	SecurityPolicy   []policy
	WorkspaceName    string
	PackFormat       string
	PackArtifact     string
	ManifestConcepts []string
	Projections      []projection
}

type compositionCase struct {
	Name         string
	Kind         string
	Concepts     []string
	Dependencies []string
	Tools        []string
	Peers        []string
	Targets      []string
	RunTargets   []string
	Projections  []string
	HasPack      bool
}

type model struct {
	Package  string
	Concepts []concept
	Cases    []compositionCase
}

func main() {
	if len(os.Args) < 2 {
		fatal("usage: generate-concepts <generate|check> -input concepts.oct -output builtin_registry.generated.go -test-output builtin_registry.generated_test.go")
	}
	command := os.Args[1]
	flags := flag.NewFlagSet("generate-concepts "+command, flag.ExitOnError)
	input := flags.String("input", "", "Oct concept generator")
	output := flags.String("output", "", "generated registry Go")
	testOutput := flags.String("test-output", "", "generated resolver expectations Go")
	flags.Parse(os.Args[2:])
	if *input == "" || *output == "" || *testOutput == "" {
		fatal("-input, -output, and -test-output are required")
	}

	value, err := experimental.Execute(*input)
	if err != nil {
		fatal("execute: %v", err)
	}
	decoded, err := decodeModel(value, *input)
	if err != nil {
		fatal("decode: %v", err)
	}
	registry, err := renderRegistry(decoded)
	if err != nil {
		fatal("render registry: %v", err)
	}
	expectations, err := renderExpectations(decoded)
	if err != nil {
		fatal("render expectations: %v", err)
	}
	artifacts := []experimental.Artifact{{Path: *output, Content: registry}, {Path: *testOutput, Content: expectations}}
	switch command {
	case "generate":
		err = experimental.Write(*input, artifacts)
	case "check":
		err = experimental.Check(*input, artifacts)
	default:
		fatal("unknown command %q; expected generate or check", command)
	}
	if err != nil {
		fatal("%s: %v", command, err)
	}
}

func decodeModel(value experimental.Value, provenance string) (model, error) {
	if value.Kind != experimental.ValueRecord || value.Record.TypeName != "GeneratedTSPackConceptRegistry" {
		return model{}, modelError(provenance, "Generate must return GeneratedTSPackConceptRegistry")
	}
	packageName, err := requiredString(value.Record.Fields, "Package", provenance)
	if err != nil {
		return model{}, err
	}
	if packageName != "concepts" {
		return model{}, modelError(provenance, "Package must be concepts, got %q", packageName)
	}
	conceptValues, err := requiredArray(value.Record.Fields, "Concepts", provenance)
	if err != nil {
		return model{}, err
	}
	if len(conceptValues) < 10 {
		return model{}, modelError(provenance, "Concepts must contain at least ten concepts")
	}
	decoded := model{Package: packageName, Concepts: make([]concept, 0, len(conceptValues))}
	seen := map[string]struct{}{}
	for index, item := range conceptValues {
		entry, err := decodeConcept(item, provenance, index)
		if err != nil {
			return model{}, err
		}
		if _, exists := seen[entry.Name]; exists {
			return model{}, modelError(provenance, "Concepts[%d].Name %q is duplicated", index, entry.Name)
		}
		seen[entry.Name] = struct{}{}
		decoded.Concepts = append(decoded.Concepts, entry)
	}
	caseValues, err := requiredArray(value.Record.Fields, "Cases", provenance)
	if err != nil {
		return model{}, err
	}
	if len(caseValues) < 3 {
		return model{}, modelError(provenance, "Cases must contain at least three coordinated resolver cases")
	}
	decoded.Cases = make([]compositionCase, 0, len(caseValues))
	for index, item := range caseValues {
		entry, err := decodeCase(item, provenance, index, seen)
		if err != nil {
			return model{}, err
		}
		decoded.Cases = append(decoded.Cases, entry)
	}
	return decoded, nil
}

func decodeConcept(value experimental.Value, provenance string, index int) (concept, error) {
	if value.Kind != experimental.ValueRecord || value.Record.TypeName != "Concept" {
		return concept{}, modelError(provenance, "Concepts[%d] must be Concept", index)
	}
	fields := value.Record.Fields
	entry := concept{}
	var err error
	for _, target := range []struct {
		name string
		out  *string
	}{{"Name", &entry.Name}, {"Description", &entry.Description}, {"WorkspaceName", &entry.WorkspaceName}, {"PackFormat", &entry.PackFormat}, {"PackArtifact", &entry.PackArtifact}} {
		*target.out, err = requiredString(fields, target.name, provenance)
		if err != nil {
			return concept{}, err
		}
	}
	if entry.Name == "" {
		return concept{}, modelError(provenance, "Concepts[%d].Name must not be empty", index)
	}
	entry.Provides, err = stringList(fields, "Provides", provenance)
	if err != nil {
		return concept{}, err
	}
	if len(entry.Provides) != 1 || entry.Provides[0] != entry.Name {
		return concept{}, modelError(provenance, "Concepts[%d].Provides must derive the concept name", index)
	}
	for _, target := range []struct {
		name string
		out  *[]string
	}{{"Requires", &entry.Requires}, {"Conflicts", &entry.Conflicts}, {"CompatibleKinds", &entry.CompatibleKinds}, {"ManifestConcepts", &entry.ManifestConcepts}} {
		*target.out, err = stringList(fields, target.name, provenance)
		if err != nil {
			return concept{}, err
		}
	}
	if len(entry.ManifestConcepts) != 1 || entry.ManifestConcepts[0] != entry.Name {
		return concept{}, modelError(provenance, "Concepts[%d].ManifestConcepts must derive the concept name", index)
	}
	if entry.Dependencies, err = dependencyList(fields, "Dependencies", provenance); err != nil {
		return concept{}, err
	}
	if entry.Tools, err = dependencyList(fields, "Tools", provenance); err != nil {
		return concept{}, err
	}
	if entry.Peers, err = dependencyList(fields, "Peers", provenance); err != nil {
		return concept{}, err
	}
	if entry.Targets, err = targetList(fields, "Targets", provenance); err != nil {
		return concept{}, err
	}
	if entry.RunTargets, err = runTargetList(fields, "RunTargets", provenance); err != nil {
		return concept{}, err
	}
	if entry.UpdatePolicy, err = policyList(fields, "UpdatePolicy", provenance); err != nil {
		return concept{}, err
	}
	if entry.SecurityPolicy, err = policyList(fields, "SecurityPolicy", provenance); err != nil {
		return concept{}, err
	}
	if entry.Projections, err = projectionList(fields, "Projections", provenance); err != nil {
		return concept{}, err
	}
	return entry, nil
}

func decodeCase(value experimental.Value, provenance string, index int, concepts map[string]struct{}) (compositionCase, error) {
	if value.Kind != experimental.ValueRecord || value.Record.TypeName != "CompositionCase" {
		return compositionCase{}, modelError(provenance, "Cases[%d] must be CompositionCase", index)
	}
	fields := value.Record.Fields
	entry := compositionCase{}
	var err error
	entry.Name, err = requiredString(fields, "Name", provenance)
	if err != nil {
		return compositionCase{}, err
	}
	entry.Kind, err = requiredString(fields, "Kind", provenance)
	if err != nil {
		return compositionCase{}, err
	}
	for _, target := range []struct {
		name string
		out  *[]string
	}{{"Concepts", &entry.Concepts}, {"Dependencies", &entry.Dependencies}, {"Tools", &entry.Tools}, {"Peers", &entry.Peers}, {"Targets", &entry.Targets}, {"RunTargets", &entry.RunTargets}, {"Projections", &entry.Projections}} {
		*target.out, err = stringList(fields, target.name, provenance)
		if err != nil {
			return compositionCase{}, err
		}
	}
	for _, name := range entry.Concepts {
		if _, ok := concepts[name]; !ok {
			return compositionCase{}, modelError(provenance, "Cases[%d] references unknown concept %q", index, name)
		}
	}
	packed, ok := fields["HasPack"]
	if !ok || packed.Kind != experimental.ValueBool {
		return compositionCase{}, modelError(provenance, "Cases[%d].HasPack must be Bool", index)
	}
	entry.HasPack = packed.Bool
	return entry, nil
}

func requiredString(fields map[string]experimental.Value, name, provenance string) (string, error) {
	value, ok := fields[name]
	if !ok || value.Kind != experimental.ValueString {
		return "", modelError(provenance, "%s must be String", name)
	}
	return value.Text, nil
}

func requiredArray(fields map[string]experimental.Value, name, provenance string) ([]experimental.Value, error) {
	value, ok := fields[name]
	if !ok || value.Kind != experimental.ValueArray {
		return nil, modelError(provenance, "%s must be an array", name)
	}
	return value.Array, nil
}

func stringList(fields map[string]experimental.Value, name, provenance string) ([]string, error) {
	values, err := requiredArray(fields, name, provenance)
	if err != nil {
		return nil, err
	}
	result := make([]string, 0, len(values))
	seen := map[string]struct{}{}
	for index, value := range values {
		if value.Kind != experimental.ValueString || value.Text == "" {
			return nil, modelError(provenance, "%s[%d] must be a non-empty String", name, index)
		}
		if _, exists := seen[value.Text]; exists {
			return nil, modelError(provenance, "%s[%d] duplicates %q", name, index, value.Text)
		}
		seen[value.Text] = struct{}{}
		result = append(result, value.Text)
	}
	return result, nil
}

func dependencyList(fields map[string]experimental.Value, name, provenance string) ([]dependency, error) {
	values, err := requiredArray(fields, name, provenance)
	if err != nil {
		return nil, err
	}
	result := make([]dependency, 0, len(values))
	for index, value := range values {
		if value.Kind != experimental.ValueRecord || value.Record.TypeName != "Dependency" {
			return nil, modelError(provenance, "%s[%d] must be Dependency", name, index)
		}
		entry := dependency{}
		entry.Name, err = requiredString(value.Record.Fields, "Name", provenance)
		if err != nil {
			return nil, err
		}
		entry.Range, err = requiredString(value.Record.Fields, "Range", provenance)
		if err != nil {
			return nil, err
		}
		entry.Source, err = requiredString(value.Record.Fields, "Source", provenance)
		if err != nil {
			return nil, err
		}
		if entry.Name == "" || entry.Source != "npm" {
			return nil, modelError(provenance, "%s[%d] must have a name and derived npm source", name, index)
		}
		result = append(result, entry)
	}
	return result, nil
}

func targetList(fields map[string]experimental.Value, name, provenance string) ([]target, error) {
	values, err := requiredArray(fields, name, provenance)
	if err != nil {
		return nil, err
	}
	result := make([]target, 0, len(values))
	for index, value := range values {
		if value.Kind != experimental.ValueRecord || value.Record.TypeName != "Target" {
			return nil, modelError(provenance, "%s[%d] must be Target", name, index)
		}
		entry := target{}
		for _, field := range []struct {
			name string
			out  *string
		}{{"Name", &entry.Name}, {"Export", &entry.Export}, {"Entry", &entry.Entry}, {"Runtime", &entry.Runtime}, {"Types", &entry.Types}} {
			entryValue, fieldErr := requiredString(value.Record.Fields, field.name, provenance)
			if fieldErr != nil {
				return nil, fieldErr
			}
			*field.out = entryValue
		}
		result = append(result, entry)
	}
	return result, nil
}

func runTargetList(fields map[string]experimental.Value, name, provenance string) ([]runTarget, error) {
	values, err := requiredArray(fields, name, provenance)
	if err != nil {
		return nil, err
	}
	result := make([]runTarget, 0, len(values))
	for index, value := range values {
		if value.Kind != experimental.ValueRecord || value.Record.TypeName != "RunTarget" {
			return nil, modelError(provenance, "%s[%d] must be RunTarget", name, index)
		}
		entry := runTarget{}
		entry.Name, err = requiredString(value.Record.Fields, "Name", provenance)
		if err != nil {
			return nil, err
		}
		entry.Command, err = requiredString(value.Record.Fields, "Command", provenance)
		if err != nil {
			return nil, err
		}
		result = append(result, entry)
	}
	return result, nil
}

func policyList(fields map[string]experimental.Value, name, provenance string) ([]policy, error) {
	values, err := requiredArray(fields, name, provenance)
	if err != nil {
		return nil, err
	}
	result := make([]policy, 0, len(values))
	for index, value := range values {
		if value.Kind != experimental.ValueRecord || value.Record.TypeName != "Policy" {
			return nil, modelError(provenance, "%s[%d] must be Policy", name, index)
		}
		entry := policy{}
		entry.Subject, err = requiredString(value.Record.Fields, "Subject", provenance)
		if err != nil {
			return nil, err
		}
		entry.Action, err = requiredString(value.Record.Fields, "Action", provenance)
		if err != nil {
			return nil, err
		}
		entry.Range, err = requiredString(value.Record.Fields, "Range", provenance)
		if err != nil {
			return nil, err
		}
		result = append(result, entry)
	}
	return result, nil
}

func projectionList(fields map[string]experimental.Value, name, provenance string) ([]projection, error) {
	values, err := requiredArray(fields, name, provenance)
	if err != nil {
		return nil, err
	}
	result := make([]projection, 0, len(values))
	for index, value := range values {
		if value.Kind != experimental.ValueRecord || value.Record.TypeName != "Projection" {
			return nil, modelError(provenance, "%s[%d] must be Projection", name, index)
		}
		entry := projection{}
		entry.Object, err = requiredString(value.Record.Fields, "Object", provenance)
		if err != nil {
			return nil, err
		}
		entry.Key, err = requiredString(value.Record.Fields, "Key", provenance)
		if err != nil {
			return nil, err
		}
		entry.Value, err = requiredString(value.Record.Fields, "Value", provenance)
		if err != nil {
			return nil, err
		}
		result = append(result, entry)
	}
	return result, nil
}

func renderRegistry(value model) ([]byte, error) {
	fset, layout := newLayout()
	decl := &ast.FuncDecl{Name: layout.ident("builtinFragments"), Type: &ast.FuncType{Results: &ast.FieldList{List: []*ast.Field{{Type: sliceType("Fragment", layout)}}}}, Body: &ast.BlockStmt{List: []ast.Stmt{&ast.ReturnStmt{Results: []ast.Expr{fragmentSlice(value.Concepts, layout)}}}}}
	return formatFile(fset, value.Package, []ast.Decl{decl})
}

func renderExpectations(value model) ([]byte, error) {
	fset, layout := newLayout()
	typeDecl := &ast.GenDecl{
		Tok: token.TYPE,
		Specs: []ast.Spec{&ast.TypeSpec{
			Name: ast.NewIdent("generatedCompositionCase"),
			Type: &ast.StructType{Fields: &ast.FieldList{List: []*ast.Field{
				fieldDecl("Name", "string"),
				fieldDecl("Kind", "string"),
				fieldDecl("Concepts", "[]string"),
				fieldDecl("Dependencies", "[]string"),
				fieldDecl("Tools", "[]string"),
				fieldDecl("Peers", "[]string"),
				fieldDecl("Targets", "[]string"),
				fieldDecl("RunTargets", "[]string"),
				fieldDecl("Projections", "[]string"),
				fieldDecl("HasPack", "bool"),
			}}},
		}},
	}
	variable := &ast.GenDecl{Tok: token.VAR, Specs: []ast.Spec{&ast.ValueSpec{Names: []*ast.Ident{layout.ident("generatedBuiltinCompositionCases")}, Type: sliceType("generatedCompositionCase", layout), Values: []ast.Expr{caseSlice(value.Cases, layout)}}}}
	names := make([]string, 0, len(value.Concepts))
	for _, concept := range value.Concepts {
		names = append(names, concept.Name)
	}
	namesVariable := &ast.GenDecl{Tok: token.VAR, Specs: []ast.Spec{&ast.ValueSpec{Names: []*ast.Ident{layout.ident("generatedBuiltinNames")}, Type: sliceType("string", layout), Values: []ast.Expr{stringSlice(names, layout)}}}}
	return formatFile(fset, value.Package, []ast.Decl{typeDecl, namesVariable, variable})
}

func formatFile(fset *token.FileSet, packageName string, declarations []ast.Decl) ([]byte, error) {
	file := &ast.File{Name: ast.NewIdent(packageName), Decls: declarations}
	var formatted bytes.Buffer
	if err := format.Node(&formatted, fset, file); err != nil {
		return nil, err
	}
	return append([]byte(generatedHeader), formatted.Bytes()...), nil
}

func fragmentSlice(values []concept, layout *sourceLayout) ast.Expr {
	elements := make([]ast.Expr, 0, len(values))
	for _, value := range values {
		layout.nextLine()
		elements = append(elements, fragmentLiteral(value, layout))
	}
	layout.nextLine()
	return &ast.CompositeLit{Type: sliceType("Fragment", layout), Lbrace: layout.take(), Elts: elements}
}

func fragmentLiteral(value concept, layout *sourceLayout) ast.Expr {
	manifest := []ast.Expr{}
	if value.WorkspaceName != "" {
		manifest = append(manifest, keyed("Workspace", pointerComposite("WorkspaceContribution", []ast.Expr{keyed("Name", stringLiteral(value.WorkspaceName, layout), layout)}, layout), layout))
	}
	if len(value.Dependencies) > 0 {
		manifest = append(manifest, keyed("Dependencies", dependencySlice(value.Dependencies, layout), layout))
	}
	if len(value.Tools) > 0 {
		manifest = append(manifest, keyed("Tools", dependencySlice(value.Tools, layout), layout))
	}
	if len(value.Peers) > 0 {
		manifest = append(manifest, keyed("Peers", dependencySlice(value.Peers, layout), layout))
	}
	if len(value.Targets) > 0 {
		manifest = append(manifest, keyed("Targets", targetSlice(value.Targets, layout), layout))
	}
	if len(value.RunTargets) > 0 {
		manifest = append(manifest, keyed("RunTargets", runTargetSlice(value.RunTargets, layout), layout))
	}
	if len(value.UpdatePolicy) > 0 {
		manifest = append(manifest, keyed("UpdatePolicy", policySlice(value.UpdatePolicy, layout), layout))
	}
	if len(value.SecurityPolicy) > 0 {
		manifest = append(manifest, keyed("SecurityPolicy", policySlice(value.SecurityPolicy, layout), layout))
	}
	if value.PackFormat != "" {
		manifest = append(manifest, keyed("Pack", pointerComposite("PackContribution", []ast.Expr{keyed("Format", stringLiteral(value.PackFormat, layout), layout), keyed("Artifact", stringLiteral(value.PackArtifact, layout), layout)}, layout), layout))
	}
	manifest = append(manifest, keyed("Concepts", stringSlice(value.ManifestConcepts, layout), layout))
	fields := []ast.Expr{keyed("Name", stringLiteral(value.Name, layout), layout)}
	if value.Description != "" {
		fields = append(fields, keyed("Description", stringLiteral(value.Description, layout), layout))
	}
	fields = append(fields, keyed("Provides", stringSlice(value.Provides, layout), layout))
	if len(value.Requires) > 0 {
		fields = append(fields, keyed("Requires", stringSlice(value.Requires, layout), layout))
	}
	if len(value.Conflicts) > 0 {
		fields = append(fields, keyed("Conflicts", stringSlice(value.Conflicts, layout), layout))
	}
	if len(value.CompatibleKinds) > 0 {
		fields = append(fields, keyed("CompatibleKinds", stringSlice(value.CompatibleKinds, layout), layout))
	}
	fields = append(fields, keyed("Manifest", composite("ManifestContributions", manifest, layout), layout))
	if len(value.Projections) > 0 {
		fields = append(fields, keyed("Projections", projectionContribution(value.Projections, layout), layout))
	}
	return composite("Fragment", fields, layout)
}

func caseSlice(values []compositionCase, layout *sourceLayout) ast.Expr {
	elements := make([]ast.Expr, 0, len(values))
	for _, value := range values {
		layout.nextLine()
		elements = append(elements, composite("generatedCompositionCase", []ast.Expr{
			keyed("Name", stringLiteral(value.Name, layout), layout), keyed("Kind", stringLiteral(value.Kind, layout), layout), keyed("Concepts", stringSlice(value.Concepts, layout), layout), keyed("Dependencies", stringSlice(value.Dependencies, layout), layout), keyed("Tools", stringSlice(value.Tools, layout), layout), keyed("Peers", stringSlice(value.Peers, layout), layout), keyed("Targets", stringSlice(value.Targets, layout), layout), keyed("RunTargets", stringSlice(value.RunTargets, layout), layout), keyed("Projections", stringSlice(value.Projections, layout), layout), keyed("HasPack", boolLiteral(value.HasPack, layout), layout),
		}, layout))
	}
	return &ast.CompositeLit{Type: sliceType("generatedCompositionCase", layout), Lbrace: layout.take(), Elts: elements}
}

func stringSlice(values []string, layout *sourceLayout) ast.Expr {
	elements := make([]ast.Expr, 0, len(values))
	for _, value := range values {
		elements = append(elements, stringLiteral(value, layout))
	}
	return &ast.CompositeLit{Type: sliceType("string", layout), Lbrace: layout.take(), Elts: elements}
}

func dependencySlice(values []dependency, layout *sourceLayout) ast.Expr {
	elements := make([]ast.Expr, 0, len(values))
	for _, value := range values {
		elements = append(elements, composite("DependencyContribution", []ast.Expr{keyed("Name", stringLiteral(value.Name, layout), layout), keyed("Range", stringLiteral(value.Range, layout), layout), keyed("Source", stringLiteral(value.Source, layout), layout)}, layout))
	}
	return &ast.CompositeLit{Type: sliceType("DependencyContribution", layout), Lbrace: layout.take(), Elts: elements}
}
func targetSlice(values []target, layout *sourceLayout) ast.Expr {
	elements := make([]ast.Expr, 0, len(values))
	for _, value := range values {
		elements = append(elements, composite("TargetContribution", []ast.Expr{keyed("Name", stringLiteral(value.Name, layout), layout), keyed("Export", stringLiteral(value.Export, layout), layout), keyed("Entry", stringLiteral(value.Entry, layout), layout), keyed("Runtime", stringLiteral(value.Runtime, layout), layout), keyed("Types", stringLiteral(value.Types, layout), layout)}, layout))
	}
	return &ast.CompositeLit{Type: sliceType("TargetContribution", layout), Lbrace: layout.take(), Elts: elements}
}
func runTargetSlice(values []runTarget, layout *sourceLayout) ast.Expr {
	elements := make([]ast.Expr, 0, len(values))
	for _, value := range values {
		elements = append(elements, composite("RunTargetContribution", []ast.Expr{keyed("Name", stringLiteral(value.Name, layout), layout), keyed("Command", stringLiteral(value.Command, layout), layout)}, layout))
	}
	return &ast.CompositeLit{Type: sliceType("RunTargetContribution", layout), Lbrace: layout.take(), Elts: elements}
}
func policySlice(values []policy, layout *sourceLayout) ast.Expr {
	elements := make([]ast.Expr, 0, len(values))
	for _, value := range values {
		elements = append(elements, composite("PolicyContribution", []ast.Expr{keyed("Subject", stringLiteral(value.Subject, layout), layout), keyed("Action", stringLiteral(value.Action, layout), layout), keyed("Range", stringLiteral(value.Range, layout), layout)}, layout))
	}
	return &ast.CompositeLit{Type: sliceType("PolicyContribution", layout), Lbrace: layout.take(), Elts: elements}
}

func projectionContribution(values []projection, layout *sourceLayout) ast.Expr {
	objects := map[string][]projection{}
	order := []string{}
	for _, value := range values {
		if _, ok := objects[value.Object]; !ok {
			order = append(order, value.Object)
		}
		objects[value.Object] = append(objects[value.Object], value)
	}
	objectEntries := make([]ast.Expr, 0, len(order))
	for _, object := range order {
		fields := make([]ast.Expr, 0, len(objects[object]))
		for _, value := range objects[object] {
			fields = append(fields, &ast.KeyValueExpr{Key: stringLiteral(value.Key, layout), Value: stringLiteral(value.Value, layout)})
		}
		objectEntries = append(objectEntries, &ast.KeyValueExpr{Key: stringLiteral(object, layout), Value: &ast.CompositeLit{Type: &ast.MapType{Key: layout.ident("string"), Value: layout.ident("string")}, Lbrace: layout.take(), Elts: fields}})
	}
	objectsLiteral := &ast.CompositeLit{Type: &ast.MapType{Key: layout.ident("string"), Value: &ast.MapType{Key: layout.ident("string"), Value: layout.ident("string")}}, Lbrace: layout.take(), Elts: objectEntries}
	return composite("ProjectionContributions", []ast.Expr{keyed("Objects", objectsLiteral, layout)}, layout)
}

func fieldDecl(name, typeName string) *ast.Field {
	return &ast.Field{Names: []*ast.Ident{ast.NewIdent(name)}, Type: parseType(typeName)}
}
func parseType(name string) ast.Expr {
	if len(name) > 2 && name[:2] == "[]" {
		return &ast.ArrayType{Elt: ast.NewIdent(name[2:])}
	}
	return ast.NewIdent(name)
}
func sliceType(name string, layout *sourceLayout) *ast.ArrayType {
	return &ast.ArrayType{Lbrack: layout.take(), Elt: layout.ident(name)}
}
func composite(typeName string, fields []ast.Expr, layout *sourceLayout) *ast.CompositeLit {
	for range fields {
		layout.nextLine()
	}
	return &ast.CompositeLit{Type: layout.ident(typeName), Lbrace: layout.take(), Elts: fields}
}
func pointerComposite(typeName string, fields []ast.Expr, layout *sourceLayout) *ast.UnaryExpr {
	return &ast.UnaryExpr{OpPos: layout.take(), Op: token.AND, X: composite(typeName, fields, layout)}
}
func keyed(name string, value ast.Expr, layout *sourceLayout) *ast.KeyValueExpr {
	return &ast.KeyValueExpr{Key: layout.ident(name), Colon: layout.take(), Value: value}
}
func stringLiteral(value string, layout *sourceLayout) *ast.BasicLit {
	return &ast.BasicLit{ValuePos: layout.take(), Kind: token.STRING, Value: fmt.Sprintf("%q", value)}
}
func boolLiteral(value bool, layout *sourceLayout) *ast.Ident {
	if value {
		return layout.ident("true")
	}
	return layout.ident("false")
}

type sourceLayout struct{ next token.Pos }

func newLayout() (*token.FileSet, *sourceLayout) {
	fset := token.NewFileSet()
	file := fset.AddFile("tspack-octgen.generated.go", -1, 500000)
	content := make([]byte, 500000)
	for index := 9; index < len(content); index += 10 {
		content[index] = '\n'
	}
	file.SetLinesForContent(content)
	return fset, &sourceLayout{next: token.Pos(file.Base())}
}
func (layout *sourceLayout) take() token.Pos { position := layout.next; layout.next++; return position }
func (layout *sourceLayout) ident(name string) *ast.Ident {
	return &ast.Ident{Name: name, NamePos: layout.take()}
}
func (layout *sourceLayout) nextLine() {
	offset := int(layout.next - 1)
	layout.next = token.Pos(((offset/10)+1)*10 + 1)
}
func modelError(provenance, format string, arguments ...any) error {
	return fmt.Errorf("TSPack OctGen model %s: %s", provenance, fmt.Sprintf(format, arguments...))
}
func fatal(format string, arguments ...any) {
	fmt.Fprintf(os.Stderr, "generate-concepts: "+format+"\n", arguments...)
	os.Exit(1)
}
