package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestMigrateMissingPackageJSONDiagnostic(t *testing.T) {
	root := t.TempDir()
	cfg, diags := parseMigrateArgs([]string{"migrate", "--root", root})
	if len(diags) != 0 {
		t.Fatalf("unexpected parse diagnostics: %#v", diags)
	}
	_, diagnostic := buildMigrationDraft(cfg)
	if diagnostic == nil {
		t.Fatalf("expected missing package.json diagnostic")
	}
	if diagnostic.Code != "TSPACK_MIGRATE_PACKAGE_JSON_MISSING" {
		t.Fatalf("unexpected diagnostic code: %s", diagnostic.Code)
	}
	if !strings.Contains(strings.Join(diagnostic.Details, "\n"), filepath.Join(root, "package.json")) {
		t.Fatalf("diagnostic details should include package.json path: %#v", diagnostic.Details)
	}
}

func TestMigrateInvalidPackageJSONDiagnostic(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "package.json"), []byte(`{"name":`), 0o644); err != nil {
		t.Fatal(err)
	}
	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root})
	_, diagnostic := buildMigrationDraft(cfg)
	if diagnostic == nil {
		t.Fatalf("expected invalid package.json diagnostic")
	}
	if diagnostic.Code != "TSPACK_MIGRATE_PACKAGE_JSON_INVALID" {
		t.Fatalf("unexpected diagnostic code: %s", diagnostic.Code)
	}
}

func TestMigrateMinimalPackageDraftAndReport(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{
  "name": "minimal",
  "version": "0.1.0",
  "license": "MIT"
}`)

	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root})
	draft, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}

	for _, want := range []string{
		`name="minimal"`,
		`version="0.1.0"`,
		`license="MIT"`,
		`kind="library"`,
		`MIGRATION_TODO_TARGETS`,
		`MIGRATION_TODO_PUBLISH`,
		`<Publish`,
	} {
		if !strings.Contains(draft.Manifest, want) {
			t.Fatalf("manifest missing %q:\n%s", want, draft.Manifest)
		}
	}
	for _, want := range []string{
		"# TSPack Migration Report",
		"## Inputs",
		"## Summary",
		"## Mechanical mappings",
		"## TODOs for human/LLM review",
		"## Scripts not migrated",
		"## Suggested next steps",
	} {
		if !strings.Contains(draft.Report, want) {
			t.Fatalf("report missing %q:\n%s", want, draft.Report)
		}
	}
}

func TestMigrateDryRunWritesNothing(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{"name":"dry","version":"1.0.0"}`)

	cmd := exec.Command("go", "run", "./cmd/tspack", "migrate", "--root", root)
	cmd.Dir = repoRootForMigrateTest(t)
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("dry-run failed: %v\n%s", err, string(output))
	}
	text := string(output)
	if !strings.Contains(text, "Migration draft planned") || !strings.Contains(text, "Run with --write") {
		t.Fatalf("unexpected dry-run output:\n%s", text)
	}
	assertFileMissing(t, filepath.Join(root, "manifest.migrated.tsx"))
	assertFileMissing(t, filepath.Join(root, "tspack-migration.md"))
}

func TestMigrateWriteForceAndAllOrNothing(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{"name":"writer","version":"1.0.0","dependencies":{"react-dom":"^19"}}`)
	repo := repoRootForMigrateTest(t)

	cmd := exec.Command("go", "run", "./cmd/tspack", "migrate", "--root", root, "--write")
	cmd.Dir = repo
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("write failed: %v\n%s", err, string(output))
	}
	manifestPath := filepath.Join(root, "manifest.migrated.tsx")
	reportPath := filepath.Join(root, "tspack-migration.md")
	assertFileContains(t, manifestPath, `reactDom: dep(npm("react-dom", "^19"))`)
	assertFileContains(t, reportPath, "TSPack Migration Report")

	if err := os.Remove(reportPath); err != nil {
		t.Fatal(err)
	}
	cmd = exec.Command("go", "run", "./cmd/tspack", "migrate", "--root", root, "--write")
	cmd.Dir = repo
	output, err = cmd.CombinedOutput()
	if err == nil {
		t.Fatalf("expected collision failure:\n%s", string(output))
	}
	if !strings.Contains(string(output), "TSPACK_MIGRATE_OUTPUT_EXISTS") {
		t.Fatalf("collision output missing diagnostic:\n%s", string(output))
	}
	assertFileMissing(t, reportPath)

	if err := os.WriteFile(manifestPath, []byte("old manifest"), 0o644); err != nil {
		t.Fatal(err)
	}
	cmd = exec.Command("go", "run", "./cmd/tspack", "migrate", "--root", root, "--write", "--force")
	cmd.Dir = repo
	output, err = cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("force write failed: %v\n%s", err, string(output))
	}
	assertFileContains(t, manifestPath, "Generated by `tspack migrate`")
	assertFileContains(t, reportPath, "## Suggested next steps")
}

func TestMigrateMetadataKindDependenciesTargetsPublishAndScripts(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{
  "name": "@acme/components",
  "version": "0.2.0",
  "license": "Apache-2.0",
  "exports": {
    ".": { "types": "./dist/index.d.ts", "import": "./dist/index.js" },
    "./react": { "types": "./dist/react/index.d.ts", "default": "./dist/react/index.js" }
  },
  "files": ["dist/**", "README.md"],
  "dependencies": { "@scope/pkg": "^1.0.0", "react": "^19.0.0" },
  "peerDependencies": { "react": "^19.0.0" },
  "peerDependenciesMeta": { "react": { "optional": true } },
  "devDependencies": { "typescript": "^5.9.0", "unknown-tool": "1.0.0" },
  "optionalDependencies": { "fsevents": "^2.3.0" },
  "scripts": { "dev": "vite", "postinstall": "node install.js" }
}`)

	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root})
	draft, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}

	manifest := draft.Manifest
	for _, want := range []string{
		`name="@acme/components"`,
		`version="0.2.0"`,
		`license="Apache-2.0"`,
		`kind="library"`,
		`react: peer(npm("react", "^19.0.0"), { optional: true })`,
		`scopePkg: dep(npm("@scope/pkg", "^1.0.0"))`,
		`fsevents: dep(npm("fsevents", "^2.3.0"))`,
		`typescript: tool(npm("typescript", "^5.9.0"))`,
		`unknownTool: tool(npm("unknown-tool", "1.0.0"))`,
		`name: "core"`,
		`name: "react"`,
		`include={["dist/**", "README.md"]}`,
		`MIGRATION_TODO_RUN_TARGETS`,
		`MIGRATION_TODO_SECURITY`,
	} {
		if !strings.Contains(manifest, want) {
			t.Fatalf("manifest missing %q:\n%s", want, manifest)
		}
	}
	if strings.Contains(manifest, `react: dep(`) {
		t.Fatalf("duplicate dependency should prefer peer classification:\n%s", manifest)
	}
	for _, want := range []string{"Duplicate dependency/peer declarations preferred peer classification", "`dev`: `vite`", "`postinstall`: `node install.js`"} {
		if !strings.Contains(draft.Report, want) {
			t.Fatalf("report missing %q:\n%s", want, draft.Report)
		}
	}
}

func TestMigratePrivateAppInferenceAndConservativePublish(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{"name":"app","version":"1.0.0","private":true}`)
	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root})
	draft, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}
	for _, want := range []string{`kind="app"`, `name: "app"`, `runtime: "dist/main.js"`, `types: ""`, `include={["dist/**", "README.md", "LICENSE"]}`} {
		if !strings.Contains(draft.Manifest, want) {
			t.Fatalf("app manifest missing %q:\n%s", want, draft.Manifest)
		}
	}
}

func TestMigrateIdentifierCollisionsAreReported(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{
  "name":"collide",
  "version":"1.0.0",
  "dependencies": {
    "@scope/pkg": "1.0.0",
    "scope-pkg": "2.0.0"
  }
}`)
	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root})
	draft, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}
	if !strings.Contains(draft.Manifest, "scopePkg2") {
		t.Fatalf("expected deterministic suffixed identifier:\n%s", draft.Manifest)
	}
	if !strings.Contains(draft.Report, "Identifier collisions") {
		t.Fatalf("expected collision report:\n%s", draft.Report)
	}
}

func TestMigrateReportStableAcrossRepeatedRuns(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{"name":"stable","version":"1.0.0","devDependencies":{"z":"1","a":"1"},"scripts":{"test":"echo test","build":"echo build"}}`)
	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root})
	first, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}
	second, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}
	if first.Manifest != second.Manifest {
		t.Fatalf("manifest is not stable")
	}
	if first.Report != second.Report {
		t.Fatalf("report is not stable")
	}
}

func TestMigratePackageLockEvidenceReport(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{
  "name": "locked",
  "version": "1.0.0",
  "dependencies": { "react": "^18.3.1" },
  "devDependencies": { "vite": "^5.0.0" },
  "peerDependencies": { "@types/react": "^18.3.0" }
}`)
	writePackageLock(t, root, `{
  "name": "locked",
  "lockfileVersion": 3,
  "packages": {
    "": {
      "name": "locked",
      "dependencies": { "react": "^18.3.1", "left-pad": "^1.3.0" },
      "devDependencies": { "vite": "^5.0.0" },
      "peerDependencies": { "@types/react": "^18.3.0" }
    },
    "node_modules/react": {
      "version": "18.3.1",
      "resolved": "https://registry.npmjs.org/react/-/react-18.3.1.tgz",
      "integrity": "sha512-reactintegritylongvalue",
      "peerDependencies": { "loose-envify": "^1.1.0" }
    },
    "node_modules/vite": {
      "version": "5.4.0",
      "resolved": "https://registry.npmjs.org/vite/-/vite-5.4.0.tgz",
      "integrity": "sha512-viteintegritylongvalue",
      "dependencies": { "esbuild": "^0.21.0" },
      "bin": { "vite": "bin/openChrome.applescript" }
    },
    "node_modules/esbuild": {
      "version": "0.21.5",
      "dependencies": { "@esbuild/linux-x64": "0.21.5" },
      "bin": { "esbuild": "bin/esbuild" },
      "scripts": { "postinstall": "node install.js" }
    },
    "node_modules/@esbuild/linux-x64": {
      "version": "0.21.5",
      "os": ["linux"],
      "cpu": ["x64"]
    },
    "node_modules/@types/react": {
      "version": "18.3.3"
    },
    "node_modules/a/node_modules/react": {
      "name": "react",
      "version": "17.0.2"
    }
  }
}`)

	cfg, diags := parseMigrateArgs([]string{"migrate", "--root", root})
	if len(diags) != 0 {
		t.Fatalf("unexpected parse diagnostics: %#v", diags)
	}
	draft, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}

	for _, want := range []string{
		"## Lockfile evidence",
		"lockfileVersion: `3`",
		"| `react` | `^18.3.1` | `18.3.1` | `dep` |",
		"| `vite` | `^5.0.0` | `5.4.0` | `tool` |",
		"### Lifecycle capabilities",
		"`esbuild@0.21.5` | `postinstall` | `node install.js`",
		"### Binary packages",
		"`vite@5.4.0`",
		"### Peer evidence",
		"`react@18.3.1`",
		"### Platform/native package evidence",
		"`@esbuild/linux-x64@0.21.5`",
		"duplicate locked versions for `react`",
		"lock root dependencies not declared in package.json fields consumed by migrate: `left-pad`",
		"lock evidence includes type packages needing type-policy review: `@types/react`",
		"Lock evidence detected 1 dependency lifecycle script capabilities",
	} {
		if !strings.Contains(draft.Report, want) {
			t.Fatalf("report missing %q:\n%s", want, draft.Report)
		}
	}
	if strings.Contains(draft.Manifest, "node install.js") {
		t.Fatalf("manifest should not include detailed lock script commands:\n%s", draft.Manifest)
	}
}

func TestMigrateImplicitPackageLockInvalidWarnsAndContinues(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{"name":"badlock","version":"1.0.0"}`)
	writePackageLock(t, root, `{"lockfileVersion":3,`)

	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root})
	draft, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("implicit invalid lock should not fail: %#v", diagnostic)
	}
	if len(draft.Diagnostics) != 1 || draft.Diagnostics[0].Code != "TSPACK_MIGRATE_PACKAGE_LOCK_INVALID" {
		t.Fatalf("expected warning diagnostic: %#v", draft.Diagnostics)
	}
	if !strings.Contains(draft.Report, "lock evidence: invalid; ignored") {
		t.Fatalf("report should mention invalid ignored lock:\n%s", draft.Report)
	}
}

func TestMigrateExplicitPackageLockMissingAndInvalidFail(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{"name":"explicit","version":"1.0.0"}`)

	cfg, _ := parseMigrateArgs([]string{"migrate", "--root", root, "--package-lock", "missing-lock.json"})
	_, diagnostic := buildMigrationDraft(cfg)
	if diagnostic == nil || diagnostic.Code != "TSPACK_MIGRATE_PACKAGE_LOCK_MISSING" {
		t.Fatalf("expected explicit missing lock diagnostic: %#v", diagnostic)
	}

	badPath := filepath.Join(root, "bad-lock.json")
	if err := os.WriteFile(badPath, []byte(`{"lockfileVersion":3,`), 0o644); err != nil {
		t.Fatal(err)
	}
	cfg, _ = parseMigrateArgs([]string{"migrate", "--root", root, "--package-lock", badPath})
	_, diagnostic = buildMigrationDraft(cfg)
	if diagnostic == nil || diagnostic.Code != "TSPACK_MIGRATE_PACKAGE_LOCK_INVALID" {
		t.Fatalf("expected explicit invalid lock diagnostic: %#v", diagnostic)
	}
}

func TestMigrateNoLockEvidenceSkipsExistingLock(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{"name":"skiplock","version":"1.0.0","dependencies":{"react":"^18"}}`)
	writePackageLock(t, root, `{"lockfileVersion":3,"packages":{"node_modules/react":{"version":"18.3.1"}}}`)

	cfg, diags := parseMigrateArgs([]string{"migrate", "--root", root, "--no-lock-evidence"})
	if len(diags) != 0 {
		t.Fatalf("unexpected diagnostics: %#v", diags)
	}
	draft, diagnostic := buildMigrationDraft(cfg)
	if diagnostic != nil {
		t.Fatalf("unexpected diagnostic: %#v", diagnostic)
	}
	if !strings.Contains(draft.Report, "lock evidence: skipped by `--no-lock-evidence`") {
		t.Fatalf("report should mention skipped lock evidence:\n%s", draft.Report)
	}

	_, diags = parseMigrateArgs([]string{"migrate", "--root", root, "--package-lock", "package-lock.json", "--no-lock-evidence"})
	if len(diags) != 1 || diags[0].Code != "TSPACK_MIGRATE_INVALID_ARGS" {
		t.Fatalf("expected invalid args diagnostic: %#v", diags)
	}
}

func TestMigrateWriteWithLockEvidenceDoesNotWriteTsLock(t *testing.T) {
	root := t.TempDir()
	writePackageJSON(t, root, `{"name":"writelock","version":"1.0.0","dependencies":{"react":"^18"}}`)
	writePackageLock(t, root, `{"lockfileVersion":3,"packages":{"node_modules/react":{"version":"18.3.1"}}}`)
	repo := repoRootForMigrateTest(t)

	cmd := exec.Command("go", "run", "./cmd/tspack", "migrate", "--root", root, "--write")
	cmd.Dir = repo
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("write with lock failed: %v\n%s", err, string(output))
	}
	assertFileContains(t, filepath.Join(root, "tspack-migration.md"), "## Lockfile evidence")
	assertFileContains(t, filepath.Join(root, "tspack-migration.md"), "| `react` | `^18` | `18.3.1` | `dep` |")
	assertFileMissing(t, filepath.Join(root, "ts-lock.toml"))
}

func writePackageJSON(t *testing.T, root string, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(root, "package.json"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func writePackageLock(t *testing.T, root string, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(root, "package-lock.json"), []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func assertFileMissing(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); err == nil {
		t.Fatalf("expected file to be missing: %s", path)
	} else if !os.IsNotExist(err) {
		t.Fatalf("unexpected stat error for %s: %v", path, err)
	}
}

func assertFileContains(t *testing.T, path string, want string) {
	t.Helper()
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(content), want) {
		t.Fatalf("%s missing %q:\n%s", path, want, string(content))
	}
}

func repoRootForMigrateTest(t *testing.T) string {
	t.Helper()
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	return filepath.Clean(filepath.Join(wd, "..", ".."))
}
