[lock]
format = 1

[[package]]
ID = 'workspace:@tspack-examples/runtime-switch-ui#3f006ed91aef579d7dd2d3e020c9432ee04bf249bac9b0f20235abd14611c111'
Name = '@tspack-examples/runtime-switch-ui'
Version = '0.1.0'
Source = 'workspace'
Integrity = ''
Repo = ''
Rev = ''
TreeHash = ''
Path = '.'
Workspace = '@tspack-examples/runtime-switch-ui'
Hash = 'sha256:3f006ed91aef579d7dd2d3e020c9432ee04bf249bac9b0f20235abd14611c111'

[[edge]]
From = '@tspack-examples/runtime-switch-app:target:app'
To = 'workspace:@tspack-examples/runtime-switch-ui#3f006ed91aef579d7dd2d3e020c9432ee04bf249bac9b0f20235abd14611c111'
Kind = 'runtime'
Optional = false

[[target]]
Package = '@tspack-examples/runtime-switch-app'
Name = 'app'
Export = '.'
Entry = 'src/app/index.ts'
Runtime = 'public/app.js'
Types = 'public/app.d.ts'

[[target]]
Package = '@tspack-examples/runtime-switch-ui'
Name = 'ui'
Export = '.'
Entry = 'src/ui/index.ts'
Runtime = 'dist/ui/index.js'
Types = 'dist/ui/index.d.ts'
