package main

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
)

var requiredBridges = []string{
	"cli.js",
	"inspect-cli.js",
	"native-test-cli.js",
}

func main() {
	distDir := filepath.Join("manifest-frontend", "dist")
	if _, err := os.Stat(distDir); err != nil {
		fatalf("missing manifest frontend dist directory %s; run: cd manifest-frontend && npm run build", distDir)
	}
	bundleDir := bundleBridgeEntrypoints(distDir)
	assets := map[string][]byte{
		"package.json": []byte("{\"type\":\"commonjs\"}\n"),
	}
	for _, bridgeName := range requiredBridges {
		path := filepath.Join(bundleDir, bridgeName)
		content, err := os.ReadFile(path)
		if err != nil {
			fatalf("missing bundled bridge %s: %v", path, err)
		}
		assets[bridgeName] = content
	}

	output, err := renderAssets(assets)
	if err != nil {
		fatalf("render generated assets: %v", err)
	}
	outPath := filepath.Join("internal", "embeddedbridges", "generated_assets.go")
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		fatalf("create output directory: %v", err)
	}
	if err := os.WriteFile(outPath, output, 0o644); err != nil {
		fatalf("write %s: %v", outPath, err)
	}
}

func bundleBridgeEntrypoints(distDir string) string {
	esbuildPath := filepath.Join("manifest-frontend", "node_modules", ".bin", "esbuild")
	if _, err := os.Stat(esbuildPath); err != nil {
		fatalf("missing esbuild at %s; run: cd manifest-frontend && npm install", esbuildPath)
	}
	bundleDir, err := os.MkdirTemp("", "tspack-bridge-bundle-*")
	if err != nil {
		fatalf("create bridge bundle temp directory: %v", err)
	}
	args := []string{}
	for _, bridgeName := range requiredBridges {
		args = append(args, filepath.Join(distDir, bridgeName))
	}
	args = append(args,
		"--bundle",
		"--platform=node",
		"--format=cjs",
		"--external:chromium-bidi/lib/cjs/bidiMapper/BidiMapper",
		"--external:chromium-bidi/lib/cjs/cdp/CdpConnection",
		"--outdir="+bundleDir,
	)
	cmd := exec.Command(esbuildPath, args...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		fatalf("bundle bridge entrypoints with esbuild: %v\n%s", err, string(output))
	}
	return bundleDir
}

func renderAssets(assets map[string][]byte) ([]byte, error) {
	names := make([]string, 0, len(assets))
	for name := range assets {
		names = append(names, name)
	}
	sort.Strings(names)

	var buffer bytes.Buffer
	buffer.WriteString("// Code generated by tools/generate-embedded-bridges; DO NOT EDIT.\n")
	buffer.WriteString("//go:build tspack_embedded_bridges\n\n")
	buffer.WriteString("package embeddedbridges\n\n")
	buffer.WriteString("import \"encoding/base64\"\n\n")
	buffer.WriteString("var Assets = map[string][]byte{\n")
	for _, name := range names {
		encoded := base64.StdEncoding.EncodeToString(assets[name])
		buffer.WriteString(fmt.Sprintf("\t%q: mustDecode(%q),\n", name, encoded))
	}
	buffer.WriteString("}\n\n")
	buffer.WriteString("func mustDecode(value string) []byte {\n")
	buffer.WriteString("\tdecoded, err := base64.StdEncoding.DecodeString(value)\n")
	buffer.WriteString("\tif err != nil {\n")
	buffer.WriteString("\t\tpanic(err)\n")
	buffer.WriteString("\t}\n")
	buffer.WriteString("\treturn decoded\n")
	buffer.WriteString("}\n")
	return format.Source(buffer.Bytes())
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "generate-embedded-bridges: "+format+"\n", args...)
	os.Exit(1)
}
